[package]
name = "narf-block"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "NARF block device abstraction"

[dependencies]
narf-lib = { path = "../lib" }
narf-capabilities = { path = "../capabilities" }
narf-io = { path = "../io" }
narf-ipc = { path = "../ipc" }
narf-time = { path = "../time" }
narf-tracing = { path = "../tracing" }
narf-crypto  = { path = "../crypto" }
narf-tpm     = { path = "../tpm" }
narf-scheduler = { path = "../scheduler" }
async-trait = "0.1"
narf-kernel-test = { path = "../verification/kernel-test" }

[lints]
workspace = true
