//! Generated differential fuzzing of the BPF JIT against the interpreter.
//!
//! Every other JIT-vs-interpreter comparison in the tree is a *hand-written*
//! case: someone thought of a shape and wrote it down. That finds the bugs
//! somebody suspected. This finds the rest — random well-formed programs,
//! loaded, compiled, and run both ways, compared through the one comparison
//! [`super::diff_run`] implements (results, trap *discriminants*, and the
//! `is_jited()` assertion that stops a fallen-back subject comparing the
//! interpreter with itself).
//!
//! ## Well-formed by construction, not by rejection sampling
//!
//! A generator that emits random 64-bit words tests the verifier's rejection
//! path and nothing else — it would produce a compiled subject roughly never.
//! This one is built the other way round: every invariant the verifier checks
//! is maintained *while generating*, so the program is well-formed before it is
//! ever handed to `verify`.
//!
//! * **No uninitialised reads.** A prologue writes every one of R0..R9 before
//!   the body starts, and each kfunc call is immediately followed by a re-init
//!   of R1..R5 — the registers the BPF ABI declares caller-saved. Any point the
//!   generator is willing to *branch to* therefore has all ten registers live.
//! * **No writes to R10**, and R10 is never read except as the base of a stack
//!   access, so no scalar can become a pointer by accident.
//! * **Stack accesses are pre-filled.** Every offset the body can load from is
//!   written by the prologue, so a load is always in-bounds *and* reads a value
//!   this run wrote. That second half is what makes the comparison sound at
//!   all: the two runs happen back to back on the same program, so a program
//!   whose output depended on residue from the previous run would diverge for
//!   reasons that are not a JIT bug.
//! * **Context reads happen first**, while R1 still holds the context pointer.
//! * **Branch targets are patched after layout**, from a list of indices the
//!   generator recorded as safe, so a target is always in range and always a
//!   point where the register invariant holds.
//! * **Dead calls are neutralised.** The verifier's fixpoint does not analyse
//!   unreachable code, so a `call` a jump made unreachable has no resolved call
//!   site and the whole program falls back. A reachability pass rewrites those
//!   to a move — see [`neutralise_dead_calls`].
//!
//! The instruction *repertoire* is deliberately exactly what the backends
//! lower: a shape neither backend emits (`div`, `mod`, `LD_IMM64`, atomics,
//! byte-swap, sub-doubleword and sign-extending memory access) would make every
//! program containing it fall back, and a fuzzer whose subjects fall back is a
//! fuzzer comparing the interpreter with itself.
//! [`smoke_bpf_jit_fuzz_unlowered_shapes_still_fall_back`] pins that boundary,
//! so extending a backend makes this module's repertoire go stale *loudly*.
//!
//! ## Determinism and replay
//!
//! One seed per program, derived from a base seed by a mixing step, so
//! iteration *k* is reproducible without replaying iterations 0..k. On a
//! divergence the failing seed is printed and the same program can be
//! regenerated by adding the seed to [`PINNED_SEEDS`], which
//! [`smoke_bpf_jit_fuzz_replays_pinned_seeds`] runs on every boot. That test is
//! the permanent home for anything this fuzzer finds.
//!
//! The base seed is a constant, so an unmodified tree fuzzes the *same* corpus
//! every boot — a CI failure is reproducible by definition. `bpf_fuzz_seed=`
//! and `bpf_fuzz_n=` on the kernel cmdline move it off that corpus for a soak
//! run without changing what CI does:
//!
//! ```text
//! XTASK_QEMU_APPEND='bpf_fuzz_n=4000' cargo xtask test --arch=x86_64 \
//!     --subsystem bpf/fuzz
//! ```
//!
//! These register under `bpf/fuzz` rather than `bpf` so that soak is one boot
//! of five tests rather than the whole subsystem. `subsystem_selected` matches
//! on `/` boundaries, so `--subsystem bpf` still picks them up and the default
//! suite is unchanged.
//!
//! `bpf_fuzz_trace` prints each seed *before* its program runs. That is for the
//! one failure class a differential cannot report at all: a miscompile that
//! corrupts control flow rather than a value takes the kernel down inside the
//! native run, so nothing is left to compare and nothing is printed afterwards.
//! Dropping the aarch64 `x30` save does exactly that — the mutation is caught,
//! in that the suite dies, but only the trace says on which seed.

use alloc::vec::Vec;

use narf_bpf_isa::{AluOp, CondOp, Decoded, Size, Source};
use narf_kernel_test::{kernel_test_in, TestResult};

use super::{asm, call, call_arena_base, diff_run, load, r, NOT_COMPILED, NO_BACKEND};
use crate::interp::Outcome;
use narf_bpf_verifier::kfunc::Context;

/// Write a line to the console.
///
/// [`TestResult::Fail`] carries a `&'static str`, so a failing *seed* — the
/// one thing that makes a generated failure actionable — cannot be reported
/// through the result. It is printed instead, next to the test's own output.
macro_rules! note {
    ($($arg:tt)*) => {{
        use core::fmt::Write as _;
        let _ = writeln!(narf_console::Writer, $($arg)*);
    }};
}

// ── knobs ───────────────────────────────────────────────────────────

/// Programs per run of the straight-line/branch fuzzer.
///
/// Small on purpose: this runs in the default `xtask test` suite, and a
/// differential that doubles the suite's runtime gets disabled rather than
/// fixed. `bpf_fuzz_n=` raises it for a soak.
const DEFAULT_ITERS: u32 = 128;

/// Programs per run of the arena fuzzer. Fewer, because each one allocates and
/// tears down an arena group.
const DEFAULT_ARENA_ITERS: u32 = 48;

/// The corpus every unmodified boot fuzzes. Changing this changes what CI
/// covers, which is a deliberate act and not a side effect of a rebuild.
const BASE_SEED: u64 = 0x4E41_5246_0BFF_0001;

/// The floor the compiled/generated ratio must clear.
///
/// Not 100%: the verifier's fixpoint does not analyse code it proves
/// unreachable, and a randomly generated predicate is sometimes decidable, so
/// an occasional `call` in a provably-dead arm leaves the program without a
/// resolved call site and it falls back. That is a *correct* fallback. What the
/// floor rules out is the failure mode that makes this whole module worthless —
/// a generator drifting into shapes no backend lowers, so that every
/// "comparison" is the interpreter against itself. Measured at 100% (both
/// fuzzers) on `bpf-part4`; the floor is set below the measurement so ordinary
/// noise does not make it flaky, and the *measured* number is printed every
/// run.
const MIN_COMPILED_PCT: u32 = 90;

/// The floor the verified/generated ratio must clear.
///
/// Separate from [`MIN_COMPILED_PCT`] because they are different claims. This
/// one says the generator still builds well-formed programs; that one says the
/// backends still lower them. Collapsing the two would let a generator that
/// drifted into verifier-rejected shapes hide behind a good compile rate over a
/// shrinking sample. Measured at 100% for both fuzzers on `bpf-part4` — it was
/// 94% for the arena one until the R0-still-holds-the-handle case above was
/// fixed, which is what the number is for.
const MIN_VERIFIED_PCT: u32 = 85;

/// Seeds a run of this fuzzer has already found a divergence for.
///
/// Empty means nothing has been found yet — not that nothing is checked. Every
/// entry here is replayed on every boot by
/// [`smoke_bpf_jit_fuzz_replays_pinned_seeds`], so a bug this found once cannot
/// come back without a named, deterministic test going red. Append, never
/// remove: a seed whose divergence has been fixed is exactly the seed worth
/// keeping.
const PINNED_SEEDS: &[u64] = &[
    // Not divergences — three arbitrary seeds, pinned so the replay path
    // itself is exercised on a tree where the fuzzer has found nothing. A
    // replay harness that has never run is a replay harness that does not work.
    0x0000_0000_0000_0001,
    0xDEAD_BEEF_CAFE_F00D,
    0x5A5A_5A5A_A5A5_A5A5,
];

/// `bpf_fuzz_n=<N>` from the cmdline, or `None`.
fn cmdline_iters() -> Option<u32> {
    narf_boot::cmdline()
        .split_ascii_whitespace()
        .find_map(|t| t.strip_prefix("bpf_fuzz_n="))
        .and_then(|v| v.parse::<u32>().ok())
}

/// `bpf_fuzz_seed=<N>` from the cmdline (decimal or `0x`-prefixed), or `None`.
fn cmdline_seed() -> Option<u64> {
    let v = narf_boot::cmdline()
        .split_ascii_whitespace()
        .find_map(|t| t.strip_prefix("bpf_fuzz_seed="))?;
    match v.strip_prefix("0x") {
        Some(hex) => u64::from_str_radix(hex, 16).ok(),
        None => v.parse::<u64>().ok(),
    }
}

/// Whether the cmdline asked for a seed to be printed *before* each program
/// runs (`bpf_fuzz_trace`).
///
/// Off by default because it is one console line per iteration. On for the
/// failure class a differential cannot report: a miscompile that corrupts
/// *control flow* rather than a value — a dropped `x30` save on aarch64 is the
/// canonical one — takes the kernel down inside `run_atomic`, so there is no
/// comparison left to fail and no seed printed afterwards. With this, the last
/// seed on the console is the one that did it.
fn cmdline_trace() -> bool {
    narf_boot::cmdline()
        .split_ascii_whitespace()
        .any(|t| t == "bpf_fuzz_trace")
}

// ── PRNG ────────────────────────────────────────────────────────────

/// SplitMix64.
///
/// Chosen over anything with more state because the whole point is that a
/// single `u64` reproduces a program exactly: `Rng::new(seed)` is the complete
/// input to the generator, so a printed seed *is* the failing test case.
#[derive(Clone, Copy, Debug)]
struct Rng(u64);

impl Rng {
    const fn new(seed: u64) -> Self {
        Rng(seed)
    }

    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform-ish in `0..n`. `n == 0` is treated as `1` rather than dividing
    /// by zero — no caller passes it, and a panic here would take the kernel
    /// down for a generator bug.
    fn below(&mut self, n: u32) -> u32 {
        (self.next() % u64::from(n.max(1))) as u32
    }

    fn chance(&mut self, pct: u32) -> bool {
        self.below(100) < pct
    }

    /// A boundary immediate — see [`IMM_POOL`].
    fn imm(&mut self) -> i32 {
        IMM_POOL[self.below(IMM_POOL.len() as u32) as usize]
    }

    /// A writable BPF register: R0..R9. R10 is the read-only frame pointer.
    fn reg(&mut self) -> u8 {
        self.below(10) as u8
    }
}

/// Derive iteration `k`'s seed from the base without running iterations
/// `0..k`, so a reported seed replays on its own.
fn seed_for(base: u64, k: u32) -> u64 {
    let mut s = Rng::new(base ^ (u64::from(k).wrapping_mul(0x9E37_79B9_7F4A_7C15)));
    s.next()
}

// ── generation vocabulary ───────────────────────────────────────────

/// Immediates chosen for the boundaries a code generator gets wrong:
/// sign-extension of `imm32`, and shift counts at and above both operand
/// widths (32/33 for `ALU`, 64/65 for `ALU64`, and `-1` which masks to 63/31).
const IMM_POOL: [i32; 17] = [
    0,
    1,
    -1,
    2,
    -2,
    7,
    8,
    31,
    32,
    33,
    63,
    64,
    65,
    0x7FFF,
    -0x8000,
    i32::MAX,
    i32::MIN,
];

/// Stack displacements, straddling both encoding boundaries that exist.
///
/// x86-64's `modrm_mem` switches from `disp8` to `disp32` at -128, and
/// aarch64's `LDUR`/`STUR` carry a 9-bit signed immediate that runs out at
/// -256, past which `addr_operand` materialises the displacement into a
/// scratch register. Both sides of both boundaries are here, plus a pair well
/// beyond the second so the scratch path is not only hit at its edge.
const SLOT_OFFS: [i16; 10] = [-8, -16, -120, -128, -136, -248, -256, -264, -504, -512];

/// The ALU operations both backends lower. `Div` and `Mod` are absent on
/// purpose — see the module docs and
/// [`smoke_bpf_jit_fuzz_unlowered_shapes_still_fall_back`].
const ALU_OPS: [AluOp; 9] = [
    AluOp::Add,
    AluOp::Sub,
    AluOp::Mul,
    AluOp::Or,
    AluOp::And,
    AluOp::Xor,
    AluOp::Lsh,
    AluOp::Rsh,
    AluOp::Arsh,
];

const COND_OPS: [CondOp; 11] = [
    CondOp::Eq,
    CondOp::Ne,
    CondOp::Gt,
    CondOp::Ge,
    CondOp::Lt,
    CondOp::Le,
    CondOp::Sgt,
    CondOp::Sge,
    CondOp::Slt,
    CondOp::Sle,
    CondOp::Set,
];

/// Which instruction classes a generated program actually contained.
///
/// Reported in aggregate at the end of a run. A coverage claim nobody measures
/// is a coverage claim that quietly stops being true — this is how "the fuzzer
/// generates calls" stays a fact rather than a comment.
#[derive(Clone, Copy, Debug, Default)]
struct Classes {
    alu_imm: u32,
    alu_reg: u32,
    neg: u32,
    mov: u32,
    stack_store: u32,
    stack_load: u32,
    ctx_load: u32,
    call: u32,
    fwd_branch: u32,
    back_edge: u32,
    uncond_jump: u32,
    narrow: u32,
}

impl Classes {
    fn merge(&mut self, o: &Classes) {
        self.alu_imm += o.alu_imm;
        self.alu_reg += o.alu_reg;
        self.neg += o.neg;
        self.mov += o.mov;
        self.stack_store += o.stack_store;
        self.stack_load += o.stack_load;
        self.ctx_load += o.ctx_load;
        self.call += o.call;
        self.fwd_branch += o.fwd_branch;
        self.back_edge += o.back_edge;
        self.uncond_jump += o.uncond_jump;
        self.narrow += o.narrow;
    }
}

// ── the generator ───────────────────────────────────────────────────

/// Generate one well-formed program from `seed`.
///
/// Returns the instruction list and the class census. The list always ends in
/// `Exit` and never falls off the end.
fn generate(seed: u64) -> (Vec<Decoded>, Classes) {
    let mut rng = Rng::new(seed);
    let mut prog: Vec<Decoded> = Vec::new();
    let mut cls = Classes::default();
    // Register values the verifier cannot pin to a constant. Branch conditions
    // prefer these: a predicate over two constants is decidable, the fixpoint
    // proves one arm unreachable, and a `call` in that arm never gets a
    // resolved call site — which shows up as a program that falls back rather
    // than as a bug.
    let mut opaque = [false; 10];
    // Per-slot: does this stack offset currently hold an opaque value? Used
    // for the same reason, through loads.
    let mut slot_opaque = [false; SLOT_OFFS.len()];
    let mut initialised = [false; 10];

    // Calls and context reads cannot coexist in a *compiled* program.
    //
    // `jit_glue::scan_program`'s gate 5 certifies only R10 and — whole-program,
    // not flow-sensitively — R1, and it withdraws R1 the moment the program
    // contains any `call`, because a kfunc return could put another pointer
    // class there and a back-edge could route it around to an earlier access.
    // So a program that both reads its context through R1 and calls a kfunc is
    // refused as `UncheckedPointerBase` and runs interpreted, whatever else is
    // in it.
    //
    // The first version of this generator emitted both, and every program with
    // a call in it fell back. `diff_run`'s `is_jited()` assertion is what said
    // so — loudly, and immediately. Two modes rather than one is the fix: each
    // program is *either* a context reader or a caller, so both halves of the
    // repertoire actually reach a backend.
    let call_mode = rng.chance(50);

    // ── phase A: the source of values the verifier cannot pin to a constant.
    //
    // At least one is mandatory. Without it every predicate in the program is
    // decidable, the fixpoint proves one arm of each branch unreachable, and
    // branch coverage collapses to "the arm that survived" — with the further
    // consequence that a `call` in a pruned arm has no resolved call site and
    // the program falls back.
    if call_mode {
        // A kfunc return. `narf_test_stack_residue` is pure and takes no
        // arguments, so it is deterministic at run time and opaque at verify
        // time — exactly the pair of properties this needs.
        prog.push(call("narf_test_stack_residue"));
        for k in 1..=5u8 {
            prog.push(super::mov_imm(k, rng.imm()));
            initialised[k as usize] = true;
        }
        initialised[0] = true;
        opaque[0] = true;
        cls.call += 1;
        // Spread it, so the opaque value is not confined to the one register a
        // call always writes.
        for reg in 6..10u8 {
            if rng.chance(50) {
                prog.push(super::mov_reg(reg, 0));
                initialised[reg as usize] = true;
                opaque[reg as usize] = true;
                cls.mov += 1;
            }
        }
    } else {
        // Context reads, while R1 still holds the context pointer. Phase B
        // overwrites R1, so this is the only window in which one is
        // well-typed. Read into R6..R9, which phase B then leaves alone.
        for reg in 6..10u8 {
            if rng.chance(55) {
                let word = rng.below(4) as i16;
                prog.push(Decoded::Load {
                    size: Size::Dw,
                    sign_extend: false,
                    dst: r(reg),
                    src: r(1),
                    off: word * 8,
                });
                initialised[reg as usize] = true;
                opaque[reg as usize] = true;
                cls.ctx_load += 1;
            }
        }
        if !opaque.iter().any(|&o| o) {
            prog.push(Decoded::Load {
                size: Size::Dw,
                sign_extend: false,
                dst: r(9),
                src: r(1),
                off: 0,
            });
            initialised[9] = true;
            opaque[9] = true;
            cls.ctx_load += 1;
        }
    }

    // ── phase B: initialise everything phase A did not.
    for reg in 0..10u8 {
        if !initialised[reg as usize] {
            prog.push(super::mov_imm(reg, rng.imm()));
            cls.mov += 1;
        }
    }

    // ── phase C: fill every stack offset the body may read.
    //
    // Two jobs at once. It makes every load in-bounds *and* makes the loaded
    // value a function of this run only, so the native run's writes cannot
    // change what the interpreted run reads back.
    for (k, &off) in SLOT_OFFS.iter().enumerate() {
        // Half from an opaque register, so stack loads are not all constants.
        let opaque_src = rng.chance(50);
        let src = if opaque_src {
            let s = pick_opaque(&mut rng, &opaque);
            slot_opaque[k] = true;
            Source::Reg(r(s))
        } else {
            Source::Imm(rng.imm())
        };
        prog.push(Decoded::Store {
            size: Size::Dw,
            dst: r(10),
            off,
            src,
        });
        cls.stack_store += 1;
    }

    // ── phase D: the body.
    //
    // Nothing before this point is ever a branch target, so the prologue's
    // three phases run exactly once per invocation however the body loops —
    // which is what keeps "every register initialised, every reachable stack
    // offset written" true at every target rather than only on the first pass.
    let n_units = 6 + rng.below(22) as usize;
    let mut targets: Vec<u32> = Vec::new();
    // Indices of the placeholder jumps, patched once the layout is known.
    let mut jumps: Vec<usize> = Vec::new();
    // At most one unconditional back-edge per program: it is the strongest
    // fuel-accounting case there is (a program that never terminates on its
    // own, so both paths must agree on exhaustion) and also the most
    // expensive, because both runs then burn the whole fuel budget.
    let mut uncond_budget = 1u32;

    for _ in 0..n_units {
        targets.push(prog.len() as u32);
        emit_unit(
            &mut rng,
            &mut prog,
            &mut cls,
            &mut opaque,
            &slot_opaque,
            &mut jumps,
            &mut uncond_budget,
            call_mode,
        );
    }

    // ── phase E: the result, and the exit.
    targets.push(prog.len() as u32);
    prog.push(super::mov_reg(0, rng.reg()));
    cls.mov += 1;
    prog.push(Decoded::Exit);

    patch_jumps(&mut rng, &mut prog, &targets, &jumps, &mut cls);
    neutralise_dead_calls(&mut prog);
    (prog, cls)
}

/// A register currently holding a verifier-opaque value, or R9 as a fallback.
fn pick_opaque(rng: &mut Rng, opaque: &[bool; 10]) -> u8 {
    let mut candidates = [0u8; 10];
    let mut n = 0usize;
    for (k, &o) in opaque.iter().enumerate() {
        if o {
            candidates[n] = k as u8;
            n += 1;
        }
    }
    if n == 0 {
        return 9;
    }
    candidates[rng.below(n as u32) as usize]
}

/// Emit one body unit. A unit is one or more instructions that must not be
/// jumped into the middle of.
#[allow(clippy::too_many_arguments)]
fn emit_unit(
    rng: &mut Rng,
    prog: &mut Vec<Decoded>,
    cls: &mut Classes,
    opaque: &mut [bool; 10],
    slot_opaque: &[bool; SLOT_OFFS.len()],
    jumps: &mut Vec<usize>,
    uncond_budget: &mut u32,
    call_mode: bool,
) {
    // A call in a context-reading program would withdraw R1 as a certified
    // base and make the whole thing fall back — see the mode split in
    // `generate`. Re-rolled into the neighbouring class rather than skipped, so
    // a context-mode program is not systematically shorter.
    let roll = match rng.below(100) {
        r @ 77..=85 if !call_mode => r - 40,
        r => r,
    };
    match roll {
        // ALU, immediate source.
        0..=21 => {
            let wide = rng.chance(55);
            let dst = rng.reg();
            let op = ALU_OPS[rng.below(ALU_OPS.len() as u32) as usize];
            prog.push(Decoded::Alu {
                wide,
                op,
                dst: r(dst),
                src: Source::Imm(rng.imm()),
            });
            cls.alu_imm += 1;
            if !wide {
                cls.narrow += 1;
            }
        }
        // ALU, register source.
        22..=39 => {
            let wide = rng.chance(55);
            let dst = rng.reg();
            let src = rng.reg();
            let op = ALU_OPS[rng.below(ALU_OPS.len() as u32) as usize];
            prog.push(Decoded::Alu {
                wide,
                op,
                dst: r(dst),
                src: Source::Reg(r(src)),
            });
            opaque[dst as usize] |= opaque[src as usize];
            cls.alu_reg += 1;
            if !wide {
                cls.narrow += 1;
            }
        }
        // Negate.
        40..=44 => {
            let wide = rng.chance(50);
            let dst = rng.reg();
            prog.push(Decoded::Neg { wide, dst: r(dst) });
            cls.neg += 1;
            if !wide {
                cls.narrow += 1;
            }
        }
        // Move, immediate — the only thing that *clears* opacity.
        45..=53 => {
            let wide = rng.chance(60);
            let dst = rng.reg();
            prog.push(Decoded::Mov {
                wide,
                dst: r(dst),
                src: Source::Imm(rng.imm()),
                sign_extend: None,
            });
            opaque[dst as usize] = false;
            cls.mov += 1;
            if !wide {
                cls.narrow += 1;
            }
        }
        // Move, register.
        54..=60 => {
            let wide = rng.chance(70);
            let dst = rng.reg();
            let src = rng.reg();
            prog.push(Decoded::Mov {
                wide,
                dst: r(dst),
                src: Source::Reg(r(src)),
                sign_extend: None,
            });
            opaque[dst as usize] = opaque[src as usize];
            cls.mov += 1;
            if !wide {
                cls.narrow += 1;
            }
        }
        // Stack store.
        61..=68 => {
            let k = rng.below(SLOT_OFFS.len() as u32) as usize;
            let src = if rng.chance(60) {
                Source::Reg(r(rng.reg()))
            } else {
                Source::Imm(rng.imm())
            };
            prog.push(Decoded::Store {
                size: Size::Dw,
                dst: r(10),
                off: SLOT_OFFS[k],
                src,
            });
            cls.stack_store += 1;
        }
        // Stack load. Always from an offset phase C filled, so it is in bounds
        // and reads a value this run wrote.
        69..=76 => {
            let k = rng.below(SLOT_OFFS.len() as u32) as usize;
            let dst = rng.reg();
            prog.push(Decoded::Load {
                size: Size::Dw,
                sign_extend: false,
                dst: r(dst),
                src: r(10),
                off: SLOT_OFFS[k],
            });
            // Conservative: a slot the body has overwritten may now hold
            // anything, so treat a load as opaque whenever phase C made it so.
            opaque[dst as usize] = slot_opaque[k];
            cls.stack_load += 1;
        }
        // A kfunc call, plus the re-init of the registers it clobbers.
        //
        // `narf_test_arg_mix` mixes all five argument registers with distinct
        // odd multipliers, so any *permutation* of them — the exact failure
        // both backends' argument shuffles are one edit away from — changes
        // the answer. `narf_test_stack_residue` reports the callee's own stack
        // alignment, which is otherwise invisible from BPF.
        77..=85 => {
            let five = rng.chance(70);
            if five {
                for k in 1..=5u8 {
                    prog.push(super::mov_imm(k, rng.imm()));
                }
                prog.push(call("narf_test_arg_mix"));
            } else {
                prog.push(call("narf_test_stack_residue"));
            }
            // R1..R5 are caller-saved; anything that reads them afterwards
            // reads an uninitialised register unless this runs.
            for k in 1..=5u8 {
                prog.push(super::mov_imm(k, rng.imm()));
                opaque[k as usize] = false;
            }
            // The return value is not a constant the verifier can see.
            opaque[0] = true;
            cls.call += 1;
        }
        // A jump. Target patched once the layout is known.
        _ => {
            let unconditional = *uncond_budget > 0 && rng.chance(18);
            if unconditional {
                *uncond_budget -= 1;
                jumps.push(prog.len());
                prog.push(Decoded::Jump { off: 0 });
                cls.uncond_jump += 1;
            } else {
                let wide = rng.chance(55);
                let op = COND_OPS[rng.below(COND_OPS.len() as u32) as usize];
                // Prefer an opaque destination so both arms stay feasible.
                let dst = if rng.chance(80) {
                    pick_opaque(rng, opaque)
                } else {
                    rng.reg()
                };
                let src = if rng.chance(50) {
                    Source::Reg(r(rng.reg()))
                } else {
                    Source::Imm(rng.imm())
                };
                jumps.push(prog.len());
                prog.push(Decoded::JumpCond {
                    wide,
                    op,
                    dst: r(dst),
                    src,
                    off: 0,
                });
                if !wide {
                    cls.narrow += 1;
                }
            }
        }
    }
}

/// Choose a target for every placeholder jump and write the displacement in.
///
/// Targets come from `targets`, which the generator filled with unit
/// boundaries — points where every register is initialised — so a patched jump
/// cannot land somewhere the verifier would call an uninitialised read.
fn patch_jumps(
    rng: &mut Rng,
    prog: &mut [Decoded],
    targets: &[u32],
    jumps: &[usize],
    cls: &mut Classes,
) {
    // At most one back-edge, and only from a conditional jump when the
    // unconditional budget already spent one. Both are throttled for the same
    // reason: a program that loops until fuel runs out costs the whole fuel
    // budget on *both* paths, and the suite has a time budget.
    let mut back_budget = 1u32;
    for &at in jumps {
        if targets.is_empty() {
            continue;
        }
        let mut target = targets[rng.below(targets.len() as u32) as usize] as usize;
        if target <= at {
            if back_budget == 0 {
                // Re-roll forward: the first target strictly after this jump.
                match targets.iter().find(|&&t| t as usize > at) {
                    Some(&t) => target = t as usize,
                    None => target = prog.len() - 1,
                }
            } else {
                back_budget -= 1;
            }
        }
        let disp = target as i64 - (at as i64 + 1);
        if target > at {
            cls.fwd_branch += 1;
        } else {
            cls.back_edge += 1;
        }
        match &mut prog[at] {
            Decoded::Jump { off } => *off = disp as i32,
            Decoded::JumpCond { off, .. } => *off = disp as i16,
            // The placeholder was written by this module and nothing else
            // rewrites it; an unreachable arm rather than a panic, because a
            // generator bug must not take the kernel down.
            _ => {}
        }
    }
}

/// Rewrite any `call` control flow cannot reach into a move.
///
/// The verifier's fixpoint only walks reachable code, so an unreachable `call`
/// has no entry in `kfunc_calls` — and `resolve_call` on either backend then
/// refuses the *whole program*, which falls back to the interpreter and makes
/// the comparison vacuous. The rewrite keeps the instruction count and every
/// jump displacement exactly as they were.
fn neutralise_dead_calls(prog: &mut [Decoded]) {
    let live = reachable(prog);
    for (k, insn) in prog.iter_mut().enumerate() {
        if !live[k] && matches!(insn, Decoded::Call(_)) {
            *insn = Decoded::Mov {
                wide: true,
                dst: r(0),
                src: Source::Imm(0),
                sign_extend: None,
            };
        }
    }
}

/// Which instructions control flow can reach from index 0.
fn reachable(prog: &[Decoded]) -> Vec<bool> {
    let mut seen = alloc::vec![false; prog.len()];
    let mut stack: Vec<usize> = Vec::new();
    if !prog.is_empty() {
        stack.push(0);
    }
    while let Some(k) = stack.pop() {
        if k >= prog.len() || seen[k] {
            continue;
        }
        seen[k] = true;
        let push = |t: i64, stack: &mut Vec<usize>| {
            if t >= 0 && (t as usize) < prog.len() {
                stack.push(t as usize);
            }
        };
        match prog[k] {
            Decoded::Exit => {}
            Decoded::Jump { off } => push(k as i64 + 1 + i64::from(off), &mut stack),
            Decoded::JumpCond { off, .. } => {
                push(k as i64 + 1, &mut stack);
                push(k as i64 + 1 + i64::from(off), &mut stack);
            }
            _ => push(k as i64 + 1, &mut stack),
        }
    }
    seen
}

// ── the run ─────────────────────────────────────────────────────────

/// Aggregate outcome of a fuzzing run.
#[derive(Clone, Copy, Debug, Default)]
struct Tally {
    generated: u32,
    verified: u32,
    compiled: u32,
    /// The first seed that produced a divergence, and what kind.
    failure: Option<(u64, &'static str)>,
}

/// Generate, load, compile and compare `iters` programs from `base`.
fn fuzz(base: u64, iters: u32) -> (Tally, Classes) {
    let mut tally = Tally::default();
    let mut cls = Classes::default();
    let trace = cmdline_trace();
    for k in 0..iters {
        let seed = seed_for(base, k);
        if trace {
            note!("bpf-fuzz: trying seed={seed:#018x}");
        }
        let (items, c) = generate(seed);
        cls.merge(&c);
        tally.generated += 1;
        let Ok(p) = load("fuzz", asm(&items), Context::Atomic) else {
            continue;
        };
        tally.verified += 1;
        match diff_run(&p, [7, 0x5A5A_5A5A_A5A5_A5A5, 1, u64::MAX]) {
            Ok(()) => tally.compiled += 1,
            // Nothing to compare against on this architecture — the caller
            // turns this into a Skip.
            Err(e) if e == NO_BACKEND => {
                tally.failure = Some((seed, NO_BACKEND));
                return (tally, cls);
            }
            // A gate refused the program. Counted, not failed: see
            // MIN_COMPILED_PCT for why the *rate* is the assertion.
            Err(e) if e == NOT_COMPILED => {}
            Err(e) => {
                tally.compiled += 1;
                if tally.failure.is_none() {
                    tally.failure = Some((seed, e));
                }
                return (tally, cls);
            }
        }
    }
    (tally, cls)
}

fn smoke_bpf_jit_fuzz_generated_programs_match_the_interpreter() -> TestResult {
    if !narf_bpf_jit::has_backend() {
        return TestResult::Skip(NO_BACKEND);
    }
    let base = cmdline_seed().unwrap_or(BASE_SEED);
    let iters = cmdline_iters().unwrap_or(DEFAULT_ITERS);
    let (t, cls) = fuzz(base, iters);

    if let Some((seed, why)) = t.failure {
        if why == NO_BACKEND {
            return TestResult::Skip(NO_BACKEND);
        }
        note!("bpf-fuzz: DIVERGENCE base={base:#018x} seed={seed:#018x} — {why}");
        note!("bpf-fuzz: replay with bpf_fuzz_seed={seed:#018x} bpf_fuzz_n=1, or add the seed to PINNED_SEEDS");
        dump(seed);
        return TestResult::Fail("a generated program diverged — see the printed seed");
    }

    note!(
        "bpf-fuzz: base={:#018x} n={} verified={} compiled={} ({}% of verified, {}% of generated)",
        base,
        t.generated,
        t.verified,
        t.compiled,
        pct(t.compiled, t.verified),
        pct(t.compiled, t.generated)
    );
    note!(
        "bpf-fuzz: classes alu_i={} alu_r={} neg={} mov={} st={} ld={} ctx={} call={} fwd={} back={} ja={} 32bit={}",
        cls.alu_imm,
        cls.alu_reg,
        cls.neg,
        cls.mov,
        cls.stack_store,
        cls.stack_load,
        cls.ctx_load,
        cls.call,
        cls.fwd_branch,
        cls.back_edge,
        cls.uncond_jump,
        cls.narrow
    );

    // Coverage assertions. Without these the test could stay green while the
    // generator quietly stopped producing the shapes it claims to.
    if t.generated == 0 {
        return TestResult::Fail("no programs were generated");
    }
    if pct(t.compiled, t.verified) < MIN_COMPILED_PCT {
        return TestResult::Fail(
            "too few verified programs compiled — the comparison is going vacuous",
        );
    }
    if pct(t.verified, t.generated) < MIN_VERIFIED_PCT {
        return TestResult::Fail("too few generated programs verified — the generator has drifted");
    }
    // Each of these is a class the module docs claim to generate, and each has
    // a way of quietly going to zero: `call` and `ctx` are the two *modes*, so
    // one at zero means the mode split broke; `back` is throttled by a budget
    // that could be spent wrongly; `32bit` is a coin flip inside every other
    // class. Measured counts on `bpf-part4` at n=128 are call=160, ctx=149,
    // fwd=204, back=78, ld=158, 32bit=678 — none of them marginal, so a zero
    // here is a broken generator and not a slow day.
    if cls.call == 0
        || cls.ctx_load == 0
        || cls.fwd_branch == 0
        || cls.back_edge == 0
        || cls.stack_load == 0
        || cls.narrow == 0
    {
        return TestResult::Fail("the generator stopped covering a class it claims to cover");
    }
    TestResult::Pass
}
kernel_test_in!(
    "bpf/fuzz",
    smoke_bpf_jit_fuzz_generated_programs_match_the_interpreter
);

fn pct(num: u32, den: u32) -> u32 {
    if den == 0 {
        return 0;
    }
    num * 100 / den
}

/// Print a program, so a divergence arrives with its subject attached.
///
/// One line per instruction in the same shorthand the hand-written cases use,
/// which is what makes minimising a found seed into a permanent regression
/// test a transcription job rather than a re-derivation.
fn dump(seed: u64) {
    let (items, _) = generate(seed);
    note!(
        "bpf-fuzz: program for seed {seed:#018x} ({} insns)",
        items.len()
    );
    for (k, d) in items.iter().enumerate() {
        note!("bpf-fuzz:   [{k:3}] {d:?}");
    }
}

// ── replay ──────────────────────────────────────────────────────────

fn smoke_bpf_jit_fuzz_replays_pinned_seeds() -> TestResult {
    // The permanent home for anything the fuzzer finds. A generated failure is
    // only worth as much as its replay: the seed goes in `PINNED_SEEDS` and
    // from then on it is an ordinary named test that runs every boot,
    // independent of the base seed or the iteration count.
    if !narf_bpf_jit::has_backend() {
        return TestResult::Skip(NO_BACKEND);
    }
    let mut compiled = 0u32;
    for &seed in PINNED_SEEDS {
        let (items, _) = generate(seed);
        let Ok(p) = load("fuzz_pin", asm(&items), Context::Atomic) else {
            note!("bpf-fuzz: pinned seed {seed:#018x} no longer verifies");
            return TestResult::Fail("a pinned seed no longer produces a well-formed program");
        };
        match diff_run(&p, [7, 0x5A5A_5A5A_A5A5_A5A5, 1, u64::MAX]) {
            Ok(()) => compiled += 1,
            Err(e) if e == NO_BACKEND => return TestResult::Skip(NO_BACKEND),
            Err(e) => {
                note!("bpf-fuzz: pinned seed {seed:#018x} diverged — {e}");
                dump(seed);
                return TestResult::Fail("a pinned seed diverged");
            }
        }
    }
    // A replay list where nothing compiles would pass vacuously.
    if compiled == 0 {
        return TestResult::Fail("no pinned seed compiled, so nothing was replayed");
    }
    TestResult::Pass
}
kernel_test_in!("bpf/fuzz", smoke_bpf_jit_fuzz_replays_pinned_seeds);

// ── arena fuzzing ───────────────────────────────────────────────────

/// Generate an arena program from `seed`, plus the page count of its arena.
///
/// Straight-line by construction. The arena lowering has no control flow in it,
/// and a loop over an arena would be a read-modify-write whose result depended
/// on which run went first — the native run's stores are still there when the
/// interpreted run starts, because both runs share one arena.
///
/// Every load is preceded by a store to the same effective address for the same
/// reason, so the value a load returns is a function of this program alone.
fn generate_arena(seed: u64, pages: usize) -> Vec<Decoded> {
    let mut rng = Rng::new(seed);
    let bytes = pages * 4096;
    let mut prog: Vec<Decoded> = Vec::new();

    // R0 := the arena base handle; parked in R6, which survives a call.
    prog.push(call_arena_base());
    prog.push(super::mov_reg(6, 0));
    // R0 is overwritten immediately because it still holds the *handle*, and
    // the program may end without ever loading into it — at which point `exit`
    // would be returning a pointer and the verifier refuses the program. That
    // is where the arena fuzzer's first measured verify rate of 94% went; the
    // rate is printed every run precisely so a gap like this is a number rather
    // than a guess.
    prog.push(super::mov_imm(0, rng.imm()));
    // The call clobbered R1..R5.
    for k in 1..=5u8 {
        prog.push(super::mov_imm(k, rng.imm()));
    }
    for k in 7..10u8 {
        prog.push(super::mov_imm(k, rng.imm()));
    }

    // Optional pointer arithmetic on the handle, so the displacement fold is
    // not the only thing addressing the arena.
    let mut bump: i64 = 0;
    if rng.chance(40) {
        // A page-aligned bump that leaves room for the accesses below.
        let b = (rng.below((pages as u32).max(1)) * 4096) as i64;
        if b > 0 {
            prog.push(super::alu_imm(AluOp::Add, 6, b as i32));
            bump = b;
        }
    }

    // In-bounds traffic: store then load back, at displacements including zero
    // (which the emitter shortens) and the far end of the arena.
    let room = bytes as i64 - bump;
    let n_pairs = 1 + rng.below(4) as usize;
    for _ in 0..n_pairs {
        // Aligned, in bounds, and inside `off16`.
        let max_slot = ((room - 8).max(0) / 8) as u32;
        let off = if rng.chance(25) {
            0i16
        } else {
            (rng.below(max_slot + 1) * 8) as i16
        };
        let v = rng.imm();
        prog.push(Decoded::Store {
            size: Size::Dw,
            dst: r(6),
            off,
            src: Source::Imm(v),
        });
        let dst = rng.reg();
        if dst != 6 {
            prog.push(Decoded::Load {
                size: Size::Dw,
                sign_extend: false,
                dst: r(dst),
                src: r(6),
                off,
            });
        }
    }

    // …and, sometimes, one access the arena cannot satisfy. Last, so
    // everything above still executed identically on both paths before the
    // trap. The verifier accepts these — it bounds a displacement against a
    // fixed 4 GiB window, not against this program's extent — so reaching the
    // runtime bound is the premise and not an accident.
    if rng.chance(45) {
        let off = [4096i16, 8192, 16384, 32760][rng.below(4) as usize];
        // Only actually out of bounds if it clears the arena; otherwise it is
        // just another in-bounds access, which is fine too.
        prog.push(Decoded::Store {
            size: Size::Dw,
            dst: r(6),
            off,
            src: Source::Imm(0xBAD),
        });
    }

    prog.push(super::mov_reg(
        0,
        [0u8, 1, 2, 3, 4, 5, 7, 8, 9][rng.below(9) as usize],
    ));
    prog.push(Decoded::Exit);
    prog
}

/// Load `items` against an arena group this run already owns.
///
/// Deliberately *not* [`super::arena_prog`], which reserves a fresh
/// [`ArenaSlot`](narf_memory::bpf_arena::ArenaSlot) per call. Slot VA is never
/// recycled — `ArenaSlot::reserve` bumps a cursor over a 64-slot window and
/// `ArenaSlot` has no `Drop`, on purpose, so that a stale TLB entry on a peer
/// CPU can never alias a later mapping. A per-iteration group therefore burns a
/// slot per iteration and exhausts the window; the first version of this test
/// did exactly that at 48 iterations and took every arena smoke that ran after
/// it down with it. Three groups for the whole run, shared by `Arc`, is the fix.
fn load_against(
    group: &alloc::sync::Arc<crate::arena::ArenaGroup>,
    items: &[Decoded],
) -> Option<alloc::sync::Arc<crate::prog::BpfProg>> {
    crate::prog::BpfProg::load_with_arena(
        super::load_cap(),
        crate::prog::LoadRequest {
            name: alloc::string::String::from("fuzz_arena"),
            insns: asm(items),
            context: Context::Atomic,
            maps: Vec::new(),
        },
        Some(alloc::sync::Arc::clone(group)),
    )
    .ok()
}

fn smoke_bpf_jit_fuzz_generated_arena_programs_match_the_interpreter() -> TestResult {
    // The one lowering with no bounds check in it: an arena access is a bare
    // dereference plus an exception-table entry, and the *only* thing that
    // makes an out-of-bounds one non-fatal is the fixup. Comparing trap
    // discriminants is what rules out the tempting-but-wrong fixup — Linux's
    // `ex_handler_bpf` zeroes the destination and resumes, which would make a
    // wild arena access *return a value* natively and trap interpreted.
    if !narf_bpf_jit::has_backend() {
        return TestResult::Skip(NO_BACKEND);
    }
    let base = cmdline_seed()
        .unwrap_or(BASE_SEED)
        .wrapping_mul(0x9E37_79B9_7F4A_7C15);
    let iters = cmdline_iters().map_or(DEFAULT_ARENA_ITERS, |n| n / 2 + 1);
    let mut generated = 0u32;
    let mut verified = 0u32;
    let mut compiled = 0u32;
    let mut trapped = 0u32;
    let mut returned = 0u32;

    // Three arenas for the whole run — see `load_against`. Different sizes so
    // "the far end of the arena" is a different address in each, and so the
    // out-of-bounds displacements land in bounds for the large one and past the
    // end of the small one.
    let cap = crate::arena::kernel_arena_cap();
    let mut groups: Vec<(alloc::sync::Arc<crate::arena::ArenaGroup>, usize)> = Vec::new();
    for pages in [1usize, 2, 4] {
        match crate::arena::ArenaGroup::with_one(cap, pages) {
            Ok(g) => groups.push((alloc::sync::Arc::new(g), pages)),
            Err(_) => return TestResult::Fail("could not reserve an arena for the fuzzer"),
        }
    }

    let trace = cmdline_trace();
    for k in 0..iters {
        let seed = seed_for(base, k);
        if trace {
            note!("bpf-fuzz: trying arena seed={seed:#018x}");
        }
        let (group, pages) = &groups[(k as usize) % groups.len()];
        let items = generate_arena(seed, *pages);
        generated += 1;
        let Some(p) = load_against(group, &items) else {
            continue;
        };
        verified += 1;
        match diff_run(&p, [0; 4]) {
            Ok(()) => compiled += 1,
            Err(e) if e == NO_BACKEND => return TestResult::Skip(NO_BACKEND),
            Err(e) if e == NOT_COMPILED => {}
            Err(e) => {
                note!("bpf-fuzz: ARENA DIVERGENCE base={base:#018x} seed={seed:#018x} — {e}");
                note!("bpf-fuzz: replay by adding ({seed:#018x}, {pages}) to PINNED_ARENA_SEEDS");
                for (i, d) in items.iter().enumerate() {
                    note!("bpf-fuzz:   [{i:3}] {d:?}");
                }
                return TestResult::Fail("a generated arena program diverged");
            }
        }
        match p.run_atomic([0; 4], 4) {
            Some(Outcome::Trapped(_)) => trapped += 1,
            Some(Outcome::Returned(_)) => returned += 1,
            None => {}
        }
    }

    note!(
        "bpf-fuzz: arena base={base:#018x} n={generated} verified={verified} compiled={compiled} ({}% of verified, {}% of generated) returned={returned} trapped={trapped}",
        pct(compiled, verified),
        pct(compiled, generated)
    );
    if generated == 0 {
        return TestResult::Fail("no arena programs were generated");
    }
    // The floor is on compiled-out-of-*verified*, because those are two
    // different claims: a program the verifier refuses says nothing about the
    // backends, while a verified program that falls back is a subject the
    // comparison cannot use. Both numbers are printed, so a generator drifting
    // into shapes the verifier rejects is visible rather than absorbed.
    if pct(compiled, verified) < MIN_COMPILED_PCT {
        return TestResult::Fail("too few verified arena programs compiled");
    }
    if pct(verified, generated) < MIN_VERIFIED_PCT {
        return TestResult::Fail("too few generated arena programs verified");
    }
    // Both verdicts must occur, or the sweep is only testing one of the two
    // things it exists to test.
    if trapped == 0 {
        return TestResult::Fail("no generated arena program reached the runtime bound");
    }
    if returned == 0 {
        return TestResult::Fail("no generated arena program completed");
    }
    TestResult::Pass
}
kernel_test_in!(
    "bpf/fuzz",
    smoke_bpf_jit_fuzz_generated_arena_programs_match_the_interpreter
);

/// Arena seeds to replay every boot, each with the arena size it was found on.
///
/// The arena counterpart of [`PINNED_SEEDS`]. Separate because an arena
/// program's in-bounds displacements are chosen against a page count, so a seed
/// on its own does not reproduce the program.
const PINNED_ARENA_SEEDS: &[(u64, usize)] = &[
    // Not divergences — two arbitrary seeds, so the replay path is exercised on
    // a tree where the arena fuzzer has found nothing.
    (0x0000_0000_0000_0002, 4),
    (0xD239_2D50_5322_34FF, 4),
];

fn smoke_bpf_jit_fuzz_replays_pinned_arena_seeds() -> TestResult {
    if !narf_bpf_jit::has_backend() {
        return TestResult::Skip(NO_BACKEND);
    }
    // One group for the whole test, at the largest size any pinned entry uses,
    // because arena slot VA is never recycled — see `load_against`. A seed
    // pinned against a smaller arena is replayed against this one; the
    // generator was given that seed's page count, so the *program* is identical
    // and only the arena behind it is larger, which changes nothing about what
    // the two backends do with it.
    let cap = crate::arena::kernel_arena_cap();
    let widest = PINNED_ARENA_SEEDS.iter().map(|e| e.1).max().unwrap_or(1);
    let group = match crate::arena::ArenaGroup::with_one(cap, widest) {
        Ok(g) => alloc::sync::Arc::new(g),
        Err(_) => return TestResult::Fail("could not reserve an arena for the replay"),
    };
    let mut compiled = 0u32;
    for &(seed, pages) in PINNED_ARENA_SEEDS {
        let items = generate_arena(seed, pages);
        let Some(p) = load_against(&group, &items) else {
            note!("bpf-fuzz: pinned arena seed {seed:#018x} no longer verifies");
            return TestResult::Fail("a pinned arena seed no longer produces a valid program");
        };
        match diff_run(&p, [0; 4]) {
            Ok(()) => compiled += 1,
            Err(e) if e == NO_BACKEND => return TestResult::Skip(NO_BACKEND),
            Err(e) => {
                note!("bpf-fuzz: pinned arena seed {seed:#018x} diverged — {e}");
                for (i, d) in items.iter().enumerate() {
                    note!("bpf-fuzz:   [{i:3}] {d:?}");
                }
                return TestResult::Fail("a pinned arena seed diverged");
            }
        }
    }
    if compiled == 0 {
        return TestResult::Fail("no pinned arena seed compiled, so nothing was replayed");
    }
    TestResult::Pass
}
kernel_test_in!("bpf/fuzz", smoke_bpf_jit_fuzz_replays_pinned_arena_seeds);

// ── the repertoire boundary ─────────────────────────────────────────

fn smoke_bpf_jit_fuzz_unlowered_shapes_still_fall_back() -> TestResult {
    // The generator's repertoire is "what both backends lower", which is a
    // claim about *other* files. This is that claim, executed.
    //
    // Each program below is well-formed and contains exactly one shape neither
    // backend emits, so it must load and must *not* compile. When somebody
    // teaches a backend one of these, this test goes red at that entry — which
    // is the signal to add the shape to the fuzzer's repertoire rather than to
    // leave it silently uncovered. Deleting the entry to get green is the one
    // wrong move, and saying so here is cheaper than finding out later.
    if !narf_bpf_jit::has_backend() {
        return TestResult::Skip(NO_BACKEND);
    }
    let cases: [(&str, Vec<Decoded>); 6] = [
        (
            "div",
            alloc::vec![
                super::mov_imm(0, 100),
                super::mov_imm(1, 7),
                Decoded::Div {
                    wide: true,
                    signed: false,
                    dst: r(0),
                    src: Source::Reg(r(1)),
                },
                Decoded::Exit,
            ],
        ),
        (
            "mod",
            alloc::vec![
                super::mov_imm(0, 100),
                Decoded::Mod {
                    wide: true,
                    signed: false,
                    dst: r(0),
                    src: Source::Imm(7),
                },
                Decoded::Exit,
            ],
        ),
        (
            "byte-swap",
            alloc::vec![
                super::mov_imm(0, 0x1234),
                Decoded::End {
                    dst: r(0),
                    order: narf_bpf_isa::ByteOrder::Little,
                    width: 32,
                },
                Decoded::Exit,
            ],
        ),
        (
            "narrow stack load",
            alloc::vec![
                super::st_imm(10, -8, 0x5A5A),
                Decoded::Load {
                    size: Size::W,
                    sign_extend: false,
                    dst: r(0),
                    src: r(10),
                    off: -8,
                },
                Decoded::Exit,
            ],
        ),
        (
            "sign-extending load",
            alloc::vec![
                super::st_imm(10, -8, -1),
                Decoded::Load {
                    size: Size::W,
                    sign_extend: true,
                    dst: r(0),
                    src: r(10),
                    off: -8,
                },
                Decoded::Exit,
            ],
        ),
        (
            "MOVSX",
            alloc::vec![
                super::mov_imm(0, -1),
                Decoded::Mov {
                    wide: true,
                    dst: r(0),
                    src: Source::Reg(r(0)),
                    sign_extend: Some(8),
                },
                Decoded::Exit,
            ],
        ),
    ];
    for (what, items) in cases {
        let Ok(p) = load("unlowered", asm(&items), Context::Atomic) else {
            // A shape the *verifier* refuses is not evidence about the
            // backends, and silently skipping it would hollow this out.
            note!("bpf-fuzz: the verifier rejected the '{what}' probe");
            return TestResult::Fail("an unlowered-shape probe no longer verifies");
        };
        if p.is_jited() {
            note!("bpf-fuzz: a backend now lowers '{what}' — add it to the fuzzer's repertoire");
            return TestResult::Fail(
                "a backend gained a shape the fuzzer does not generate — extend the repertoire",
            );
        }
    }
    TestResult::Pass
}
kernel_test_in!(
    "bpf/fuzz",
    smoke_bpf_jit_fuzz_unlowered_shapes_still_fall_back
);
