[package]
name         = "narf-drivers-storage"
description  = "Non-NVMe storage drivers (AHCI today; virtio-scsi later)."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lib]
name = "narf_drivers_storage"
path = "src/lib.rs"

[dependencies]
narf-lib          = { path = "../../lib" }
narf-bus          = { path = "../../bus" }
narf-capabilities = { path = "../../capabilities" }
narf-io           = { path = "../../io" }
narf-memory       = { path = "../../memory" }
narf-time         = { path = "../../time" }

[lints]
workspace = true
