[package]
name         = "narf-aml"
description  = "Minimum-viable AML (DSDT/SSDT) namespace builder."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lib]
name = "narf_aml"
path = "src/lib.rs"

[dependencies]
narf-lib         = { path = "../lib" }
narf-console     = { path = "../console" }
narf-acpi        = { path = "../acpi" }
narf-memory      = { path = "../memory" }
narf-time        = { path = "../time" }
narf-scheduler   = { path = "../scheduler" }
narf-kernel-test = { path = "../verification/kernel-test" }

[lints]
workspace = true
