[package]
name         = "narf-spdm"
description  = "SPDM 1.2 attestation and device measurement extension."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "narf_spdm"
path = "src/lib.rs"

[dependencies]
narf-lib = { path = "../lib", version = "0.1.0" }
narf-capabilities = { path = "../capabilities", version = "0.1.0" }
narf-scheduler = { path = "../scheduler", version = "0.1.0" }
narf-tpm = { path = "../tpm", version = "0.1.0" }
narf-kernel-test = { path = "../verification/kernel-test", version = "0.1.0" }
async-trait = "0.1"

[features]
kernel-test = []

[lints]
workspace = true
