[package]
name         = "narf-graphics-driver"
description  = "Display drivers: bochs-display (x86_64 q35) + future."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lib]
name = "narf_graphics_driver"
path = "src/lib.rs"

[dependencies]
narf-lib          = { path = "../../lib", version = "0.1.0" }
narf-graphics     = { path = "../../graphics", version = "0.1.0" }
narf-bus          = { path = "../../bus", version = "0.1.0" }
narf-capabilities = { path = "../../capabilities", version = "0.1.0" }
narf-memory       = { path = "../../memory", version = "0.1.0" }
narf-drivers      = { path = "../../drivers", version = "0.1.0" }
narf-init         = { path = "../../init", version = "0.1.0" }

[lints]
workspace = true
