//! Kernel symbol table — the set of symbols modules may link against.
//!
//! Mirrors Linux's `__ksymtab` / `EXPORT_SYMBOL` mechanism:
//!   * `linux/include/linux/export.h::EXPORT_SYMBOL` (`export.h:42`)
//!   * `linux/kernel/module/main.c::find_symbol` (`main.c:432`)
//!
//! Key differences in NARF:
//!   * Each export carries a `crc` — a 32-bit version hash of the
//!     symbol's type signature. A module that was compiled against
//!     a different signature gets `Mismatch` at resolution time
//!     rather than a runtime crash.
//!   * Some exports declare a `required_cap` — the module must have
//!     a matching `RequiredCap` in its manifest before the relocator
//!     resolves the reference. This makes cap requirements visible
//!     at link time, not just at first call. Linux has no equivalent.

use alloc::vec::Vec;
use core::sync::atomic::{AtomicU32, Ordering};

use narf_capabilities::CapKind;
use narf_lib::sync::IrqSafeSpinLock;

use crate::manifest::Manifest;

/// One symbol the kernel exports to modules.
///
/// Linux equivalent: `struct kernel_symbol` in `include/linux/export.h`.
#[derive(Copy, Clone, Debug)]
pub struct KernelExport {
    /// Linker-visible name (e.g. `"narf_io_alloc_coherent"`).
    pub name: &'static str,
    /// Address of the function or static the export resolves to.
    /// Stored as `usize` so const-context registration is possible
    /// without typing the closure.
    pub addr: usize,
    /// CRC of the symbol's type signature. Generated by the build
    /// at the EXPORT site; modules carry the same CRC in their
    /// relocation expectations.
    pub crc: u32,
    /// Cap holders only: a module must declare a matching RequiredCap
    /// in its manifest before the relocator will resolve a reference.
    pub required_cap: Option<CapKind>,
}

/// Resolution result.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ResolveError {
    /// Symbol absent from the kernel table.
    Unknown,
    /// Symbol present but the caller didn't declare a required cap.
    CapMissing(CapKind),
    /// CRC mismatch — kernel and module disagree on the symbol's
    /// type signature.
    CrcMismatch { expected: u32, got: u32 },
}

/// Resolved address + the export entry it came from.
#[derive(Copy, Clone, Debug)]
pub struct Resolution {
    pub addr: usize,
    pub crc: u32,
}

/// The kernel's exported symbol table. Populated at boot via
/// `register_export` (typically through the `narf_export!` macro).
static KSYMTAB: IrqSafeSpinLock<Vec<KernelExport>> = IrqSafeSpinLock::new(Vec::new());

/// Hash version of the running kernel build. Generated by the boot
/// path from the LTO image. Modules carry a `kernel_abi=` line and
/// the manifest parser rejects mismatches.
static KERNEL_ABI: AtomicU32 = AtomicU32::new(0);

/// Set the kernel ABI hash. Idempotent — overwriting with the same
/// value is a no-op; overwriting with a different value (e.g. tests)
/// just replaces.
pub fn set_kernel_abi(hash: u32) {
    KERNEL_ABI.store(hash, Ordering::Release);
}

/// Read the currently-configured kernel ABI hash.
pub fn kernel_abi() -> u32 {
    KERNEL_ABI.load(Ordering::Acquire)
}

/// Register a single kernel export. Idempotent on `name`: a second
/// call with the same name replaces the prior entry, preserving the
/// O(n) lookup invariant.
pub fn register_export(export: KernelExport) {
    let mut g = KSYMTAB.lock();
    if let Some(slot) = g.iter_mut().find(|e| e.name == export.name) {
        *slot = export;
    } else {
        g.push(export);
    }
}

/// Bulk-register a slice (compile-time table).
pub fn register_exports(exports: &[KernelExport]) {
    for e in exports {
        register_export(*e);
    }
}

/// Look up an export by name. Honours `required_cap` against the
/// caller's manifest; honours CRC if the caller supplied one.
pub fn resolve(
    name: &str,
    expected_crc: Option<u32>,
    manifest: &Manifest,
) -> Result<Resolution, ResolveError> {
    let g = KSYMTAB.lock();
    let entry = g.iter().find(|e| e.name == name).copied();
    drop(g);
    let entry = entry.ok_or(ResolveError::Unknown)?;
    if let Some(cap) = entry.required_cap {
        let has = manifest
            .required_caps
            .iter()
            .any(|rc| rc.kind == cap);
        if !has {
            return Err(ResolveError::CapMissing(cap));
        }
    }
    if let Some(want) = expected_crc {
        if want != entry.crc {
            return Err(ResolveError::CrcMismatch {
                expected: entry.crc,
                got: want,
            });
        }
    }
    Ok(Resolution {
        addr: entry.addr,
        crc: entry.crc,
    })
}

/// Number of registered exports — for `/sys/kernel/symbols_count`
/// and tests.
pub fn export_count() -> usize {
    KSYMTAB.lock().len()
}

/// Test helper: clear all exports.
#[doc(hidden)]
pub fn __reset_for_test() {
    KSYMTAB.lock().clear();
}

/// Convenience: build + register an export by parts.
///
/// Use the macro form `narf_export!(name, addr, crc)` in subsystems
/// instead of calling this directly.
pub fn export(name: &'static str, addr: usize, crc: u32) {
    register_export(KernelExport {
        name,
        addr,
        crc,
        required_cap: None,
    });
}

/// Cap-gated export.
pub fn export_with_cap(
    name: &'static str,
    addr: usize,
    crc: u32,
    required_cap: CapKind,
) {
    register_export(KernelExport {
        name,
        addr,
        crc,
        required_cap: Some(required_cap),
    });
}

/// Macro for registering a kernel symbol export at boot.
///
/// ```ignore
/// narf_modules::narf_export!("narf_io_alloc_coherent",
///     narf_io::alloc_coherent as usize, 0xABCDEF12);
/// ```
///
/// To gate on a cap:
///
/// ```ignore
/// narf_modules::narf_export!("narf_block_register",
///     narf_block::register_block_device as usize, 0x12345678,
///     narf_capabilities::CapKind::BlockDevice);
/// ```
#[macro_export]
macro_rules! narf_export {
    ($name:literal, $addr:expr, $crc:expr) => {
        $crate::symbols::export($name, $addr as usize, $crc);
    };
    ($name:literal, $addr:expr, $crc:expr, $cap:expr) => {
        $crate::symbols::export_with_cap($name, $addr as usize, $crc, $cap);
    };
}
