//! Stack canaries — per-task entropy at `gs:0x28` (x86_64) or
//! `tpidr_el0` offset on aarch64.
//!
//! The compiler-emitted side of stack-protector is enabled by passing
//! `-Z stack-protector=all` (or `=strong`) to the rustc build for
//! kernel + user code. With that flag set, every non-trivial function
//! prologue copies the canary slot into a stack frame slot and the
//! epilogue compares it against the original; mismatch fires
//! `__stack_chk_fail`, which we route into a panic + halt path.
//!
//! What this module owns:
//!
//!   1. The per-task canary value — initialised from RDRAND/RDSEED at
//!      task spawn ([`fresh_value`]).
//!   2. The MSR / TLS slot that the compiler-emitted prologues read
//!      from. On x86_64 it's `gs:0x28` (the GS-base + offset 0x28
//!      convention used by GCC/Clang and Linux's kernel canary). On
//!      aarch64 it's a fixed offset in the per-task TPIDR_EL0 block.
//!   3. The `__stack_chk_fail` symbol that the compiler-emitted
//!      epilogue jumps to on canary mismatch.
//!
//! NARF stance — leverage rustc's existing compiler-emitted scaffolding
//! rather than write our own stack-walk verifier. Linux's canary code
//! has to deal with C ABI compatibility (`%fs:0x28` glibc convention);
//! NARF's user-mode ABI is Rust-only so we standardise on rustc's
//! `-Z stack-protector` and only need to wire the MSR + the failure
//! handler.
//!
//! References:
//!   * rustc `-Z stack-protector` (added 2022, stable on aarch64 +
//!     x86_64 + risc-v).
//!   * Linux `arch/x86/include/asm/stackprotector.h` and
//!     `set_thread_area`-style canary management.
//!   * grsecurity / PaX kernel-stack-protector history (the earliest
//!     mainline Linux canary work, ca. 2006).

#![allow(dead_code)]

use core::sync::atomic::{AtomicU64, Ordering};

/// `__stack_chk_guard` is the global fallback canary the rustc/llvm
/// stack-protector lowering uses when a per-task slot isn't
/// configured. We set this once at boot (`init_global_canary`) from
/// the best entropy source available; per-task canaries override it
/// in the GS slot.
///
/// Public so the linker can resolve `__stack_chk_guard` references
/// generated by the stack-protector lowering against this storage
/// (the boot path arranges the symbol alias).
pub static STACK_CHK_GUARD: AtomicU64 = AtomicU64::new(0xDEAD_C0DE_DEAD_C0DE);

/// Per-task canary stored in the GS-base block (x86_64) or the
/// TPIDR_EL0 block (aarch64) at the architectural offset the
/// stack-protector lowering expects. The offset on x86_64 is 0x28 by
/// convention (matching glibc); on aarch64 it's whatever
/// `-Z stack-protector=strong` lowers to — currently a load through
/// `__stack_chk_guard`.
pub const X86_64_CANARY_OFFSET: u64 = 0x28;

/// Initialise the global canary slot from the best entropy source
/// available. Called once at boot, before the first stack-protected
/// function call. If init is skipped, the static initialiser
/// (`0xDEAD_C0DE_DEAD_C0DE`) leaves a constant in place — better than
/// a zero, but trivial for an attacker who can read the kernel image.
pub fn init_global_canary() {
    let v = fresh_value();
    STACK_CHK_GUARD.store(v, Ordering::Release);
}

/// Pull a fresh 64-bit canary value. Routes through
/// `narf_memory::kaslr::random_u64` so we benefit from the same
/// RDRAND/RDSEED/RNDR/TSC-mix fallback chain.
#[inline]
pub fn fresh_value() -> u64 {
    let (v, _src) = narf_memory::kaslr::random_u64();
    // Conventional Linux canary trick: zero the low byte so a
    // string-write that null-terminates ends up overflowing into the
    // canary still gets a zero in the low byte; combined with the
    // high bytes being unpredictable, this nudges naive overflow
    // attempts to be detected.
    v & !0xFF
}

/// Read the current global canary value. Useful for diagnostics and
/// for smokes that want to verify the boot path actually moved it
/// off the sentinel.
#[inline]
pub fn current_global() -> u64 {
    STACK_CHK_GUARD.load(Ordering::Acquire)
}

/// `__stack_chk_fail` — invoked by compiler-emitted epilogues on
/// canary mismatch.
///
/// `#[unsafe(no_mangle)]` so the linker resolves the symbol the
/// stack-protector lowering refers to. The behaviour: log + halt.
/// We never return.
///
/// **Smokes do not exercise this path** — calling it deliberately
/// would halt the kernel mid-test. The smoke surface checks the
/// canary storage + the init logic.
#[unsafe(no_mangle)]
pub extern "C" fn __stack_chk_fail() -> ! {
    // No panic! macro here — the canary failure means the stack
    // itself is suspect; panic's own stack walk could compound the
    // damage. Just halt.
    #[cfg(target_arch = "x86_64")]
    narf_arch::x86_64::halt_forever();
    #[cfg(target_arch = "aarch64")]
    narf_arch::aarch64::halt_forever();
    #[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
    loop {
        core::hint::spin_loop();
    }
}

/// Per-task canary block layout. On x86_64 this lives at the address
/// the GS-base register points to; offset [`X86_64_CANARY_OFFSET`]
/// (0x28) holds the value the stack-protector prologue compares
/// against. Other offsets reserved for percpu fields the kernel
/// adds (current task pointer, etc).
#[repr(C)]
pub struct CanaryBlock {
    pub _reserved: [u64; 5], // 0x00..=0x27
    pub canary: u64,         // 0x28
}

impl CanaryBlock {
    /// Fresh block populated with a new random canary.
    pub fn new() -> Self {
        Self {
            _reserved: [0; 5],
            canary: fresh_value(),
        }
    }
}

impl Default for CanaryBlock {
    fn default() -> Self {
        Self::new()
    }
}

impl core::fmt::Debug for CanaryBlock {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        // Don't leak the canary value to logs.
        f.debug_struct("CanaryBlock")
            .field("canary", &"<redacted>")
            .finish()
    }
}

// ── canary smokes ─────────────────────────────────────────────────────

use narf_kernel_test::{kernel_test_in, TestResult};

fn smoke_canary_fresh_value_nonzero_low_byte_clear() -> TestResult {
    let v = fresh_value();
    if v == 0 {
        return TestResult::Fail("fresh_value returned 0 — entropy source broken");
    }
    if v & 0xFF != 0 {
        return TestResult::Fail("low byte of canary should be cleared");
    }
    TestResult::Pass
}
kernel_test_in!(
    "frame/canary",
    smoke_canary_fresh_value_nonzero_low_byte_clear
);

fn smoke_canary_init_moves_off_sentinel() -> TestResult {
    let sentinel = 0xDEAD_C0DE_DEAD_C0DE;
    init_global_canary();
    let v = current_global();
    if v == sentinel {
        return TestResult::Fail("global canary still at sentinel after init");
    }
    if v & 0xFF != 0 {
        return TestResult::Fail("global canary low byte should be cleared");
    }
    TestResult::Pass
}
kernel_test_in!("frame/canary", smoke_canary_init_moves_off_sentinel);

fn smoke_canary_block_layout_offset_0x28() -> TestResult {
    let block = CanaryBlock::new();
    let base = &block as *const _ as usize;
    let canary_addr = &block.canary as *const _ as usize;
    let offset = canary_addr - base;
    if offset != X86_64_CANARY_OFFSET as usize {
        return TestResult::Fail("canary not at offset 0x28 — stack-protector ABI mismatch");
    }
    if block.canary == 0 {
        return TestResult::Fail("new CanaryBlock has zero canary");
    }
    TestResult::Pass
}
kernel_test_in!("frame/canary", smoke_canary_block_layout_offset_0x28);
