//! Netfilter — hook points, verdict dispatch, packet context.
//!
//! Modeled after Linux's `net/netfilter/core.c`. Five hook points per
//! family (IPv4 here; the same shapes extend to IPv6):
//!
//! - `NF_INET_PRE_ROUTING`   — after RX, before routing decision
//! - `NF_INET_LOCAL_IN`      — destined for local socket
//! - `NF_INET_FORWARD`       — being forwarded
//! - `NF_INET_LOCAL_OUT`     — generated by local socket
//! - `NF_INET_POST_ROUTING`  — about to send
//!
//! Each hook point holds an ordered list of `(priority, HookFn)` pairs
//! sorted ascending — lower priority runs first, matching
//! `nf_hook_entry_head()` ordering in Linux. A returned `Drop` /
//! `Stolen` short-circuits the chain; `Accept` continues.
//!
//! Hook ABI: `fn(&mut PktCtx) -> Verdict`. The packet context carries
//! mutable access to the L3 header and payload (so NAT can rewrite),
//! interface direction, and a slot for conntrack metadata.
//!
//! Linux refs:
//! - `net/netfilter/core.c:nf_hook_slow()` — the dispatcher loop.
//! - `include/uapi/linux/netfilter.h:42`  — `enum nf_inet_hooks`.
//! - `include/uapi/linux/netfilter.h:11`  — `NF_DROP` / `NF_ACCEPT`.

use alloc::vec::Vec;
use core::sync::atomic::{AtomicU64, Ordering};

use narf_lib::sync::IrqSafeSpinLock;

pub mod conntrack;
pub mod filter;
pub mod nat;
pub mod rules;

/// Hook point identifiers. Matches `enum nf_inet_hooks` in Linux
/// `include/uapi/linux/netfilter.h:42-49`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum HookPoint {
    PreRouting = 0,
    LocalIn = 1,
    Forward = 2,
    LocalOut = 3,
    PostRouting = 4,
}

impl HookPoint {
    pub const NUM: usize = 5;

    /// Chain name conventionally bound to this hook (matches nftables
    /// builtin-chain naming).
    pub fn chain_name(self) -> &'static str {
        match self {
            HookPoint::PreRouting => "prerouting",
            HookPoint::LocalIn => "input",
            HookPoint::Forward => "forward",
            HookPoint::LocalOut => "output",
            HookPoint::PostRouting => "postrouting",
        }
    }
}

/// Verdicts. Matches `NF_DROP` / `NF_ACCEPT` / … in Linux
/// `include/uapi/linux/netfilter.h:11-15`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Verdict {
    /// Drop the packet, no further hooks.
    Drop,
    /// Continue down the chain (and to the rest of the path).
    Accept,
    /// Some other code path took ownership (e.g. NF_QUEUE in Linux).
    Stolen,
    /// Queue to userspace. Stage-3 has no userspace queue; equivalent
    /// to `Stolen` for now.
    Queue,
    /// Re-run the chain from the start.
    Repeat,
}

/// L3 protocol. Stage-3 only needs IPv4; IPv6 is wired the same way.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum L3Proto {
    Ipv4,
    Ipv6,
}

/// L4 protocol identifier. Lifted from `include/uapi/linux/in.h`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum L4Proto {
    Icmp = 1,
    Tcp = 6,
    Udp = 17,
    Other(u8) = 255, // catch-all; payload below
}

impl L4Proto {
    pub fn from_u8(p: u8) -> L4Proto {
        match p {
            1 => L4Proto::Icmp,
            6 => L4Proto::Tcp,
            17 => L4Proto::Udp,
            _ => L4Proto::Other(p),
        }
    }

    pub fn as_u8(self) -> u8 {
        match self {
            L4Proto::Icmp => 1,
            L4Proto::Tcp => 6,
            L4Proto::Udp => 17,
            L4Proto::Other(p) => p,
        }
    }
}

/// Per-packet context handed to each hook. The payload is borrowed
/// mutably so NAT can rewrite source/dest addresses and ports in
/// place. `iface_in` / `iface_out` are short strings (interface names
/// like `"eth0"`); either may be empty depending on the hook point.
#[derive(Debug)]
pub struct PktCtx<'a> {
    pub l3_proto: L3Proto,
    pub hook: HookPoint,
    /// Inbound interface name (PRE_ROUTING / LOCAL_IN / FORWARD).
    pub iface_in: &'a str,
    /// Outbound interface name (LOCAL_OUT / FORWARD / POST_ROUTING).
    pub iface_out: &'a str,
    /// The L3 packet (IP header onwards). Hooks may rewrite in-place
    /// (NAT mangles src/dst). The slice's length doesn't change at
    /// this layer — packet length adjustment is a future concern.
    pub packet: &'a mut [u8],
    /// Optional conntrack entry id assigned by the conntrack hook.
    /// Downstream hooks (NAT) read this to find the mapping.
    pub conntrack_id: Option<u64>,
}

impl<'a> PktCtx<'a> {
    /// Construct a fresh IPv4 packet context for a given hook.
    pub fn new_ipv4(
        hook: HookPoint,
        iface_in: &'a str,
        iface_out: &'a str,
        packet: &'a mut [u8],
    ) -> Self {
        Self {
            l3_proto: L3Proto::Ipv4,
            hook,
            iface_in,
            iface_out,
            packet,
            conntrack_id: None,
        }
    }
}

/// Hook callback type. Receives mutable packet context, returns a
/// verdict.
pub type HookFn = fn(&mut PktCtx<'_>) -> Verdict;

/// One installed hook: `(priority, function)`. Lower priorities run
/// first within a hook point.
#[derive(Copy, Clone)]
struct HookEntry {
    priority: i32,
    hook_fn: HookFn,
}

impl core::fmt::Debug for HookEntry {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("HookEntry")
            .field("priority", &self.priority)
            .finish_non_exhaustive()
    }
}

/// All hooks, indexed by `HookPoint as usize`. Each slot is an
/// ordered `Vec<HookEntry>` sorted by ascending priority.
#[derive(Debug)]
pub struct HookTable {
    slots: [IrqSafeSpinLock<Vec<HookEntry>>; HookPoint::NUM],
    /// Cumulative dispatch counters per hook point (smoke instrumentation).
    counters: [AtomicU64; HookPoint::NUM],
}

impl HookTable {
    const fn new() -> Self {
        Self {
            slots: [
                IrqSafeSpinLock::new(Vec::new()),
                IrqSafeSpinLock::new(Vec::new()),
                IrqSafeSpinLock::new(Vec::new()),
                IrqSafeSpinLock::new(Vec::new()),
                IrqSafeSpinLock::new(Vec::new()),
            ],
            counters: [
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
            ],
        }
    }

    /// Register a hook at `point` with the given `priority`. Lower
    /// priorities run first. Matches Linux `nf_register_net_hook()`
    /// semantics (`net/netfilter/core.c:380`).
    pub fn register(&self, point: HookPoint, priority: i32, hook_fn: HookFn) {
        let mut slot = self.slots[point as usize].lock();
        let entry = HookEntry { priority, hook_fn };
        // Insertion-sort by ascending priority.
        let idx = slot
            .iter()
            .position(|e| e.priority > priority)
            .unwrap_or(slot.len());
        slot.insert(idx, entry);
    }

    /// Number of installed hooks at `point`.
    pub fn len(&self, point: HookPoint) -> usize {
        self.slots[point as usize].lock().len()
    }

    /// Dispatch a packet through `point`'s hook chain. Returns the
    /// first non-`Accept` verdict, or `Accept` if every hook accepted.
    /// On `Repeat` the chain is re-run from the start at most a bounded
    /// number of times to prevent infinite loops (matches Linux's
    /// implicit bound via the for-loop in `nf_hook_slow`).
    pub fn dispatch(&self, ctx: &mut PktCtx<'_>) -> Verdict {
        self.counters[ctx.hook as usize].fetch_add(1, Ordering::Relaxed);
        // Clone the function list so we don't hold the lock while
        // running user code. Hooks register rarely; this copy is cheap.
        let entries: Vec<HookEntry> = {
            let slot = self.slots[ctx.hook as usize].lock();
            slot.clone()
        };
        let mut repeats: u32 = 0;
        'outer: loop {
            for e in &entries {
                match (e.hook_fn)(ctx) {
                    Verdict::Accept => continue,
                    Verdict::Repeat => {
                        repeats += 1;
                        if repeats >= 16 {
                            return Verdict::Drop;
                        }
                        continue 'outer;
                    }
                    v => return v,
                }
            }
            return Verdict::Accept;
        }
    }

    /// Dispatch counter for `point` (smoke instrumentation).
    pub fn dispatch_count(&self, point: HookPoint) -> u64 {
        self.counters[point as usize].load(Ordering::Relaxed)
    }

    /// Wipe every hook. Test-only.
    #[doc(hidden)]
    pub fn __reset_for_test(&self) {
        for s in &self.slots {
            s.lock().clear();
        }
        for c in &self.counters {
            c.store(0, Ordering::Relaxed);
        }
    }
}

static HOOKS: HookTable = HookTable::new();

/// Global hook table.
#[inline]
pub fn hooks() -> &'static HookTable {
    &HOOKS
}

/// Convenience: register a hook on the global table.
pub fn nf_register_hook(point: HookPoint, priority: i32, hook_fn: HookFn) {
    HOOKS.register(point, priority, hook_fn);
}

/// Convenience: dispatch through the global table at `ctx.hook`.
pub fn nf_dispatch(ctx: &mut PktCtx<'_>) -> Verdict {
    HOOKS.dispatch(ctx)
}

/// Reset everything — hooks, conntrack, NAT, filter, ratelimit.
/// Test-only.
#[doc(hidden)]
pub fn __reset_all_for_test() {
    HOOKS.__reset_for_test();
    conntrack::__reset_for_test();
    nat::__reset_for_test();
    filter::__reset_for_test();
}

// ── Helpers — IPv4 header introspection ─────────────────────────────

/// 5-tuple lifted from the IPv4 + L4 header.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Tuple {
    pub src_ip: [u8; 4],
    pub dst_ip: [u8; 4],
    pub src_port: u16,
    pub dst_port: u16,
    pub proto: u8,
}

impl Tuple {
    /// "Invert" the tuple — what the *reply* tuple should look like
    /// for a normal bidirectional flow. Used by conntrack to find a
    /// matching reply.
    pub fn invert(&self) -> Tuple {
        Tuple {
            src_ip: self.dst_ip,
            dst_ip: self.src_ip,
            src_port: self.dst_port,
            dst_port: self.src_port,
            proto: self.proto,
        }
    }
}

/// Minimal IPv4 header offsets, no options. Stage-3 callers populate
/// fixed-format frames, so we can index without parsing.
pub const IPV4_OFF_PROTO: usize = 9;
pub const IPV4_OFF_SRC: usize = 12;
pub const IPV4_OFF_DST: usize = 16;
pub const IPV4_MIN_HDR_LEN: usize = 20;
pub const L4_OFF_SPORT: usize = 0;
pub const L4_OFF_DPORT: usize = 2;

/// Extract the 5-tuple from a packet whose layout is
/// `IPv4 header (20 bytes, no options) || L4 header`. For ICMP the
/// "src/dst port" fields are repurposed: `src_port = (type<<8)|code`,
/// `dst_port = id`. Returns `None` if the packet is too short.
pub fn parse_tuple_ipv4(packet: &[u8]) -> Option<Tuple> {
    if packet.len() < IPV4_MIN_HDR_LEN + 4 {
        return None;
    }
    let proto = packet[IPV4_OFF_PROTO];
    let src_ip = [
        packet[IPV4_OFF_SRC],
        packet[IPV4_OFF_SRC + 1],
        packet[IPV4_OFF_SRC + 2],
        packet[IPV4_OFF_SRC + 3],
    ];
    let dst_ip = [
        packet[IPV4_OFF_DST],
        packet[IPV4_OFF_DST + 1],
        packet[IPV4_OFF_DST + 2],
        packet[IPV4_OFF_DST + 3],
    ];
    let l4 = &packet[IPV4_MIN_HDR_LEN..];
    match L4Proto::from_u8(proto) {
        L4Proto::Tcp | L4Proto::Udp => {
            let src_port = u16::from_be_bytes([l4[L4_OFF_SPORT], l4[L4_OFF_SPORT + 1]]);
            let dst_port = u16::from_be_bytes([l4[L4_OFF_DPORT], l4[L4_OFF_DPORT + 1]]);
            Some(Tuple {
                src_ip,
                dst_ip,
                src_port,
                dst_port,
                proto,
            })
        }
        L4Proto::Icmp => {
            // type, code, checksum, id, sequence
            if l4.len() < 8 {
                return None;
            }
            let t_c = u16::from_be_bytes([l4[0], l4[1]]);
            let id = u16::from_be_bytes([l4[4], l4[5]]);
            Some(Tuple {
                src_ip,
                dst_ip,
                src_port: t_c,
                dst_port: id,
                proto,
            })
        }
        L4Proto::Other(_) => Some(Tuple {
            src_ip,
            dst_ip,
            src_port: 0,
            dst_port: 0,
            proto,
        }),
    }
}

// ── ICMP rate limiter ───────────────────────────────────────────────
//
// Token bucket bounded at 1000 tokens/sec by default — matches
// Linux's `icmp_ratelimit` netns sysctl (default 1000 ms ⇒ 1
// generation per ms ⇒ ~1000/s). We track tokens as `u32` and refill
// based on monotonic time.

/// ICMP rate limiter state.
#[derive(Debug)]
pub struct IcmpRateLimit {
    /// Tokens currently available.
    tokens: AtomicU64,
    /// Last refill time in nanoseconds (monotonic).
    last_refill_ns: AtomicU64,
    /// Maximum tokens / bucket capacity.
    capacity: u64,
    /// Refill rate in tokens-per-second.
    rate_per_sec: u64,
}

impl IcmpRateLimit {
    pub const fn new(capacity: u64, rate_per_sec: u64) -> Self {
        Self {
            tokens: AtomicU64::new(capacity),
            last_refill_ns: AtomicU64::new(0),
            capacity,
            rate_per_sec,
        }
    }

    /// Try to consume one token. Returns `true` on success (caller may
    /// send the ICMP error), `false` on rate-limit (drop instead).
    ///
    /// `now_ns` is the current monotonic time in nanoseconds. Tests
    /// inject this directly; production callers pass
    /// `narf_scheduler::narf_time::monotonic_ns()`.
    pub fn try_acquire(&self, now_ns: u64) -> bool {
        self.refill(now_ns);
        // Optimistic decrement.
        loop {
            let cur = self.tokens.load(Ordering::Acquire);
            if cur == 0 {
                return false;
            }
            if self
                .tokens
                .compare_exchange_weak(cur, cur - 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
            {
                return true;
            }
        }
    }

    /// Refill based on elapsed time since last refill. Idempotent —
    /// callers don't need to lock around it.
    fn refill(&self, now_ns: u64) {
        let last = self.last_refill_ns.load(Ordering::Acquire);
        if now_ns <= last {
            return;
        }
        let elapsed = now_ns - last;
        // Tokens-to-add = (elapsed_ns * rate) / 1e9.
        let to_add = elapsed.saturating_mul(self.rate_per_sec) / 1_000_000_000;
        if to_add == 0 {
            return;
        }
        // CAS last_refill_ns so concurrent callers don't double-count.
        if self
            .last_refill_ns
            .compare_exchange(last, now_ns, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }
        // Cap tokens at capacity.
        let mut cur = self.tokens.load(Ordering::Acquire);
        loop {
            let new = core::cmp::min(self.capacity, cur.saturating_add(to_add));
            match self
                .tokens
                .compare_exchange_weak(cur, new, Ordering::AcqRel, Ordering::Acquire)
            {
                Ok(_) => break,
                Err(actual) => cur = actual,
            }
        }
    }

    /// Currently available tokens (smoke instrumentation).
    pub fn tokens_available(&self) -> u64 {
        self.tokens.load(Ordering::Acquire)
    }

    /// Reset to full capacity at `now_ns = 0`. Test-only.
    #[doc(hidden)]
    pub fn __reset_for_test(&self) {
        self.tokens.store(self.capacity, Ordering::Release);
        self.last_refill_ns.store(0, Ordering::Release);
    }
}

/// Global ICMP rate limiter — 1000 errors / second, bucket = 1000.
static ICMP_RATELIMIT: IcmpRateLimit = IcmpRateLimit::new(1000, 1000);

/// Returns the global ICMP rate limiter.
pub fn icmp_ratelimit() -> &'static IcmpRateLimit {
    &ICMP_RATELIMIT
}
