//! GFX11 memory queue descriptor — `gfx_v11_0_gfx_mqd_init`
//! (`gfx_v11_0.c`), laid out per `v11_structs.h`.
//!
//! The MQD is the structure the command processor reads to learn what a queue
//! is: where its ring lives, how big it is, which doorbell wakes it, where to
//! report its read pointer. The driver fills one in memory and hands the
//! firmware its address; from then on the firmware owns it.
//!
//! ## Why this is an array of dwords and not a struct of 512 fields
//!
//! `struct v11_gfx_mqd` is 512 `uint32_t`s, of which `gfx_v11_0_gfx_mqd_init`
//! sets 26. Mirroring all 512 by hand would be 512 chances to put one in the
//! wrong place, and the 486 unused ones would never be checked by anything.
//! The dwords that matter are named by their INDEX, and the indices were
//! generated by compiling `v11_structs.h` on the build host and printing
//! `offsetof(struct v11_gfx_mqd, field) / 4` — the same way the UAPI struct
//! sizes are pinned. They are not arithmetic anyone did by hand.
//!
//! ## What this does not do
//!
//! LINUX-GAP: filling an MQD is not bringing a queue up. The firmware has to
//! be running first (IMU, RLC, then PFP/ME/MEC through the PSP), the doorbell
//! aperture has to be routed, and on GFX11 the queue is then handed to the MES
//! firmware with an `ADD_QUEUE` packet rather than by writing CP registers
//! directly. Each of those is a handshake with a running engine, and none of
//! it can be verified anywhere but on silicon. What is here is the part with a
//! documented layout and a checkable answer.

use narf_filesystem::FsError;

/// `sizeof(struct v11_gfx_mqd) / 4`.
pub const MQD_DWORDS: usize = 512;

// ── Field indices, generated from `v11_structs.h` ───────────────────────

pub const CP_GFX_HQD_WPTR: usize = 149;
pub const CP_GFX_HQD_WPTR_HI: usize = 150;
pub const CP_MQD_BASE_ADDR: usize = 128;
pub const CP_MQD_BASE_ADDR_HI: usize = 129;
pub const CP_GFX_MQD_CONTROL: usize = 162;
pub const CP_GFX_HQD_VMID: usize = 131;
pub const CP_GFX_HQD_QUEUE_PRIORITY: usize = 134;
pub const CP_GFX_HQD_QUANTUM: usize = 135;
pub const CP_GFX_HQD_BASE: usize = 136;
pub const CP_GFX_HQD_BASE_HI: usize = 137;
pub const CP_GFX_HQD_RPTR: usize = 138;
pub const CP_GFX_HQD_RPTR_ADDR: usize = 139;
pub const CP_GFX_HQD_RPTR_ADDR_HI: usize = 140;
pub const CP_RB_WPTR_POLL_ADDR_LO: usize = 141;
pub const CP_RB_WPTR_POLL_ADDR_HI: usize = 142;
pub const CP_RB_DOORBELL_CONTROL: usize = 143;
pub const CP_GFX_HQD_CNTL: usize = 145;
pub const CP_GFX_HQD_ACTIVE: usize = 130;
pub const SHADOW_BASE_LO: usize = 0;
pub const SHADOW_BASE_HI: usize = 1;
pub const GDS_BKUP_BASE_LO: usize = 2;
pub const GDS_BKUP_BASE_HI: usize = 3;
pub const FW_WORK_AREA_BASE_LO: usize = 4;
pub const FW_WORK_AREA_BASE_HI: usize = 5;
pub const FENCE_ADDRESS_LO: usize = 510;
pub const FENCE_ADDRESS_HI: usize = 511;

// ── Register defaults and field positions ───────────────────────────────
//
// Each `*_DEFAULT` is the register's reset value from `gc_11_0_0_default.h`,
// and `gfx_v11_0_gfx_mqd_init` builds on it rather than from zero — the
// defaults carry reserved bits that must keep their reset values.

/// `regCP_GFX_MQD_CONTROL_DEFAULT`.
const MQD_CONTROL_DEFAULT: u32 = 0x0000_0100;
const MQD_CONTROL_VMID_SHIFT: u32 = 0;
const MQD_CONTROL_VMID_MASK: u32 = 0xF;
const MQD_CONTROL_PRIV_STATE_SHIFT: u32 = 8;
const MQD_CONTROL_CACHE_POLICY_SHIFT: u32 = 24;

/// `regCP_GFX_HQD_QUANTUM_DEFAULT`.
const HQD_QUANTUM_DEFAULT: u32 = 0x0000_0a01;
const HQD_QUANTUM_EN_SHIFT: u32 = 0;

/// `regCP_GFX_HQD_CNTL_DEFAULT`.
const HQD_CNTL_DEFAULT: u32 = 0x00a0_0000;
const HQD_CNTL_RB_BUFSZ_SHIFT: u32 = 0;
const HQD_CNTL_RB_BUFSZ_MASK: u32 = 0x3F;
const HQD_CNTL_RB_BLKSZ_SHIFT: u32 = 8;
const HQD_CNTL_RB_BLKSZ_MASK: u32 = 0x3F;
const HQD_CNTL_TMZ_MATCH_SHIFT: u32 = 7;
const HQD_CNTL_RB_NON_PRIV_SHIFT: u32 = 15;

/// `regCP_RB_DOORBELL_CONTROL_DEFAULT`.
const DOORBELL_CONTROL_DEFAULT: u32 = 0;
const DOORBELL_OFFSET_SHIFT: u32 = 2;
const DOORBELL_OFFSET_MASK: u32 = 0x0FFF_FFFC >> 2;
const DOORBELL_EN_SHIFT: u32 = 30;

/// `regCP_GFX_HQD_QUEUE_PRIORITY_DEFAULT` and `regCP_GFX_HQD_RPTR_DEFAULT`.
const QUEUE_PRIORITY_DEFAULT: u32 = 0;
const HQD_RPTR_DEFAULT: u32 = 0;

/// `AMDGPU_GFX_QUEUE_PRIORITY_MAXIMUM` maps to priority level 1.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum QueuePriority {
    /// 0x0 — the default level.
    Normal,
    /// 0x1 — `AMDGPU_GFX_QUEUE_PRIORITY_MAXIMUM`.
    Maximum,
}

/// `struct amdgpu_mqd_prop` — everything the descriptor is built from.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct MqdProp {
    /// GPU address of the MQD itself. The firmware is told where to find it
    /// and the descriptor also records it.
    pub mqd_gpu_addr: u64,
    /// GPU address of the ring buffer.
    pub hqd_base_gpu_addr: u64,
    /// Where the engine writes its read pointer back.
    pub rptr_gpu_addr: u64,
    /// Where the engine polls for the host's write pointer.
    pub wptr_gpu_addr: u64,
    /// Ring size in BYTES. Must be a power of two and at least 8.
    pub queue_size: u64,
    pub doorbell_index: u32,
    pub use_doorbell: bool,
    /// A kernel queue may issue privileged packets; a userspace queue may not.
    pub kernel_queue: bool,
    pub tmz_queue: bool,
    pub priority: QueuePriority,
    /// GFX11 user-queue areas. Zero when unused.
    pub shadow_addr: u64,
    pub gds_bkup_addr: u64,
    pub csa_addr: u64,
    pub fence_address: u64,
}

fn set(mqd: &mut [u32; MQD_DWORDS], index: usize, value: u32) {
    mqd[index] = value;
}

/// Fill a GFX11 graphics MQD, following `gfx_v11_0_gfx_mqd_init` field for
/// field.
///
/// Returns the descriptor rather than writing it, so the caller decides where
/// it lives and the whole thing is checkable without a GPU.
pub fn gfx_mqd_init(prop: &MqdProp) -> Result<[u32; MQD_DWORDS], FsError> {
    // `order_base_2(queue_size / 4) - 1` underflows for anything under 8
    // bytes, and the ring must be a power of two for the buffer-size field to
    // describe it at all.
    if prop.queue_size < 8 || !prop.queue_size.is_power_of_two() {
        return Err(FsError::InvalidData);
    }
    // The ring base is stored shifted right by 8, so the low 8 bits must be
    // zero or they are silently discarded — a ring 256 bytes out of place.
    if prop.hqd_base_gpu_addr & 0xFF != 0 {
        return Err(FsError::InvalidData);
    }

    let mut mqd = [0u32; MQD_DWORDS];

    // Write pointer starts at zero.
    set(&mut mqd, CP_GFX_HQD_WPTR, 0);
    set(&mut mqd, CP_GFX_HQD_WPTR_HI, 0);

    // The descriptor records its own address. The low two bits are masked off
    // because the field is dword-aligned.
    set(
        &mut mqd,
        CP_MQD_BASE_ADDR,
        (prop.mqd_gpu_addr & 0xffff_fffc) as u32,
    );
    set(
        &mut mqd,
        CP_MQD_BASE_ADDR_HI,
        (prop.mqd_gpu_addr >> 32) as u32,
    );

    // VMID 0 and PRIV_STATE 1: the MQD itself is fetched by the firmware
    // through the kernel's address space, whatever the queue's own VMID is.
    let mut control = MQD_CONTROL_DEFAULT;
    control &= !(MQD_CONTROL_VMID_MASK << MQD_CONTROL_VMID_SHIFT);
    control |= 1 << MQD_CONTROL_PRIV_STATE_SHIFT;
    control &= !(1 << MQD_CONTROL_CACHE_POLICY_SHIFT);
    set(&mut mqd, CP_GFX_MQD_CONTROL, control);

    // The ring's VMID. Zero means the kernel's.
    set(&mut mqd, CP_GFX_HQD_VMID, 0);

    let priority = match prop.priority {
        QueuePriority::Maximum => 1,
        QueuePriority::Normal => 0,
    };
    set(
        &mut mqd,
        CP_GFX_HQD_QUEUE_PRIORITY,
        QUEUE_PRIORITY_DEFAULT | priority,
    );

    set(
        &mut mqd,
        CP_GFX_HQD_QUANTUM,
        HQD_QUANTUM_DEFAULT | (1 << HQD_QUANTUM_EN_SHIFT),
    );

    // The ring base, shifted right by 8 — the register holds a 256-byte
    // granule, which is why the alignment is checked above.
    let hqd = prop.hqd_base_gpu_addr >> 8;
    set(&mut mqd, CP_GFX_HQD_BASE, hqd as u32);
    set(&mut mqd, CP_GFX_HQD_BASE_HI, (hqd >> 32) as u32);

    // Read-pointer writeback and write-pointer poll addresses. Both high
    // halves are masked to 16 bits: the hardware takes a 48-bit address.
    set(
        &mut mqd,
        CP_GFX_HQD_RPTR_ADDR,
        (prop.rptr_gpu_addr & 0xffff_fffc) as u32,
    );
    set(
        &mut mqd,
        CP_GFX_HQD_RPTR_ADDR_HI,
        ((prop.rptr_gpu_addr >> 32) as u32) & 0xffff,
    );
    set(
        &mut mqd,
        CP_RB_WPTR_POLL_ADDR_LO,
        (prop.wptr_gpu_addr & 0xffff_fffc) as u32,
    );
    set(
        &mut mqd,
        CP_RB_WPTR_POLL_ADDR_HI,
        ((prop.wptr_gpu_addr >> 32) as u32) & 0xffff,
    );

    // `rb_bufsz = order_base_2(queue_size / 4) - 1`, in dwords.
    let rb_bufsz = (prop.queue_size / 4).trailing_zeros() - 1;
    let mut cntl = HQD_CNTL_DEFAULT;
    cntl &= !(HQD_CNTL_RB_BUFSZ_MASK << HQD_CNTL_RB_BUFSZ_SHIFT);
    cntl |= (rb_bufsz & HQD_CNTL_RB_BUFSZ_MASK) << HQD_CNTL_RB_BUFSZ_SHIFT;
    cntl &= !(HQD_CNTL_RB_BLKSZ_MASK << HQD_CNTL_RB_BLKSZ_SHIFT);
    cntl |= (rb_bufsz.wrapping_sub(2) & HQD_CNTL_RB_BLKSZ_MASK) << HQD_CNTL_RB_BLKSZ_SHIFT;
    if prop.tmz_queue {
        cntl |= 1 << HQD_CNTL_TMZ_MATCH_SHIFT;
    }
    // RB_NON_PRIV marks a queue whose packets are NOT privileged. Linux sets
    // it for a queue that is not the kernel's — so a userspace queue cannot
    // issue a privileged packet. Getting this inverted would hand every
    // userspace queue the kernel's authority over the command processor.
    if !prop.kernel_queue {
        cntl |= 1 << HQD_CNTL_RB_NON_PRIV_SHIFT;
    }
    set(&mut mqd, CP_GFX_HQD_CNTL, cntl);

    let mut doorbell = DOORBELL_CONTROL_DEFAULT;
    if prop.use_doorbell {
        doorbell |= (prop.doorbell_index & DOORBELL_OFFSET_MASK) << DOORBELL_OFFSET_SHIFT;
        doorbell |= 1 << DOORBELL_EN_SHIFT;
    }
    set(&mut mqd, CP_RB_DOORBELL_CONTROL, doorbell);

    set(&mut mqd, CP_GFX_HQD_RPTR, HQD_RPTR_DEFAULT);
    // The queue is live as far as the descriptor is concerned; the firmware
    // decides when it actually runs.
    set(&mut mqd, CP_GFX_HQD_ACTIVE, 1);

    // GFX11 user-queue areas.
    set(&mut mqd, SHADOW_BASE_LO, prop.shadow_addr as u32);
    set(&mut mqd, SHADOW_BASE_HI, (prop.shadow_addr >> 32) as u32);
    set(&mut mqd, GDS_BKUP_BASE_LO, prop.gds_bkup_addr as u32);
    set(
        &mut mqd,
        GDS_BKUP_BASE_HI,
        (prop.gds_bkup_addr >> 32) as u32,
    );
    set(&mut mqd, FW_WORK_AREA_BASE_LO, prop.csa_addr as u32);
    set(&mut mqd, FW_WORK_AREA_BASE_HI, (prop.csa_addr >> 32) as u32);
    set(&mut mqd, FENCE_ADDRESS_LO, prop.fence_address as u32);
    set(
        &mut mqd,
        FENCE_ADDRESS_HI,
        (prop.fence_address >> 32) as u32,
    );

    Ok(mqd)
}
