[package]
name = "narf-drivers-fs-squashfs"
description = "Linux-compatible read-only SquashFS 4 filesystem driver."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "narf_drivers_fs_squashfs"
path = "src/lib.rs"

[dependencies]
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }
narf-block = { path = "../../../block", version = "0.1.0" }
narf-capabilities = { path = "../../../capabilities", version = "0.1.0" }
narf-driver-runtime = { path = "../../runtime", version = "0.1.0" }
narf-filesystem = { path = "../../../filesystem", version = "0.1.0" }
narf-init = { path = "../../../init", version = "0.1.0" }
narf-io = { path = "../../../io", version = "0.1.0" }
narf-kernel-test = { path = "../../../verification/kernel-test", version = "0.1.0" }
narf-lib = { path = "../../../lib", version = "0.1.0" }
narf-memory = { path = "../../../memory", version = "0.1.0" }
narf-scheduler = { path = "../../../scheduler", version = "0.1.0" }

[lints]
workspace = true
