//! `/proc` system-state aggregate files.
//!
//! Registers the set of machine-state summary files that standard Linux
//! tools (top, ps, procps-ng, Python's psutil, etc.) read to understand
//! system health:
//!
//!   /proc/stat          — aggregate CPU time + context-switches + forks
//!   /proc/diskstats     — per-block-device I/O counters
//!   /proc/interrupts    — per-IRQ per-CPU fire counts
//!   /proc/softirqs      — per-softirq-type per-CPU counters (stub)
//!   /proc/swaps         — swap area list (header only — NARF has no swap)
//!   /proc/modules       — loadable kernel modules (deferred: LKM agent)
//!   /proc/iomem         — physical memory layout (deferred: MM wiring)
//!   /proc/ioports       — I/O port allocations (deferred: IO crate)
//!   /proc/slabinfo      — slab allocator class breakdown
//!   /proc/vmstat        — VM counter dump (mostly zeroed — deferred)
//!   /proc/zoneinfo      — per-NUMA-node zone breakdown
//!   /proc/buddyinfo     — buddy allocator free list
//!   /proc/pagetypeinfo  — page migration-type counters
//!   /proc/timer_list    — pending high-resolution timers
//!   /proc/locks         — POSIX file lock list (header only)
//!   /proc/devices       — character + block major-number table
//!   /proc/filesystems   — registered filesystem types (extends gen_filesystems)
//!   /proc/consoles      — registered console devices
//!   /proc/misc          — misc character device registrations
//!   /proc/tty/drivers   — TTY driver table
//!   /proc/fb            — framebuffer registrations
//!   /proc/crypto        — cryptographic algorithm listing
//!
//! Linux refs:
//!   fs/proc/stat.c          — show_stat
//!   fs/proc/interrupts.c    — show_interrupts
//!   fs/proc/softirqs.c      — show_softirqs
//!   block/genhd.c           — diskstats_show
//!   mm/vmstat.c             — vmstat_show / zoneinfo_show / buddyinfo_show
//!   mm/slab.c               — slab_proc_show
//!   kernel/time/timer_list.c — show_timer_list
//!   fs/locks.c              — locks_show
//!   fs/proc/devices.c       — devinfo_show
//!   drivers/char/random.c   — (for misc)
//!
//! ## Deferred wiring notes
//!
//! Per-block-device I/O counters (reads/writes/sectors/latency in
//! /proc/diskstats) are zeroed until the block layer exposes per-device
//! counters.  Most /proc/vmstat counters are also zeroed today — wiring
//! them requires adding tracking atomics throughout the MM subsystem.
//!
//! /proc/modules is an empty body until Wave-21 (LKM agent) registers its
//! module list through `register_modules_snapshot_hook`.
//!
//! /proc/iomem and /proc/ioports use placeholder "00000000-00000000 :
//! System RAM" lines pending real E820 / ACPI region export from the MM
//! and IO subsystems.

extern crate alloc;

use alloc::string::String;
use alloc::sync::Arc;
use alloc::vec::Vec;
use core::fmt::Write as _;

use narf_interrupts::{snapshot_counters, PERCPU_FIRES_MAX};
use narf_lib::smp::cpu_count;

use super::{register_proc, ProcFile};

// ── Helper: simple closure-backed ProcFile ──────────────────────────

/// A stateless `ProcFile` whose content is generated by `gen` on every
/// read. Used for files whose source data is already atomically snapshotted
/// by calling the underlying subsystem API each time.
#[derive(Debug)]
struct AggFile {
    gen: fn() -> Vec<u8>,
}

impl ProcFile for AggFile {
    fn read(&self) -> Vec<u8> {
        (self.gen)()
    }
}

#[inline]
fn agg(gen: fn() -> Vec<u8>) -> Arc<dyn ProcFile> {
    Arc::new(AggFile { gen })
}

// ── Public registration entry-point ────────────────────────────────

/// Register all aggregate `/proc` files via `register_proc`.
///
/// Called once from the filesystem init path after the dynamic registry
/// is available. Safe to call multiple times (hard cutover: the second
/// call replaces the first).
pub fn register_all() {
    register_proc("stat", agg(gen_stat));
    register_proc("diskstats", agg(gen_diskstats));
    register_proc("interrupts", agg(gen_interrupts));
    register_proc("softirqs", agg(gen_softirqs));
    register_proc("swaps", agg(gen_swaps));
    register_proc("modules", agg(gen_modules));
    register_proc("iomem", agg(gen_iomem));
    register_proc("ioports", agg(gen_ioports));
    register_proc("slabinfo", agg(gen_slabinfo));
    register_proc("vmstat", agg(gen_vmstat));
    register_proc("zoneinfo", agg(gen_zoneinfo));
    register_proc("buddyinfo", agg(gen_buddyinfo));
    register_proc("pagetypeinfo", agg(gen_pagetypeinfo));
    register_proc("timer_list", agg(gen_timer_list));
    register_proc("locks", agg(gen_locks));
    register_proc("devices", agg(gen_devices));
    register_proc("consoles", agg(gen_consoles));
    register_proc("misc", agg(gen_misc));
    register_proc("tty/drivers", agg(gen_tty_drivers));
    register_proc("fb", agg(gen_fb));
    register_proc("crypto", agg(gen_crypto));
    // /proc/filesystems is already served from ProcRoot::lookup as a
    // static file; the aggregate version here extends it with the
    // nodev annotations Linux tools expect (procps-ng checks "nodev"
    // on "proc" and "sysfs"). A second register_proc hard-cuts over
    // the old entry — correct per the registry's replacement contract.
    register_proc("filesystems", agg(gen_filesystems_annotated));
}

// ── /proc/stat ──────────────────────────────────────────────────────
//
// Linux format (kernel/time/cpufreq.c, fs/proc/stat.c):
//   cpu  <user> <nice> <system> <idle> <iowait> <irq> <softirq> <steal> <guest> <guest_nice>
//   cpu0 …
//   intr <total> [per-irq counts…]
//   ctxt <total>
//   btime <unix-seconds-at-boot>
//   processes <total forks>
//   procs_running <nr>
//   procs_blocked <nr>
//   softirq <total> [per-type]

fn gen_stat() -> Vec<u8> {
    let mut s = String::new();

    let ncpus = cpu_count().max(1) as usize;

    // Aggregate CPU line (all-zero jiffies: NARF doesn't track
    // jiffies-split today; the line is syntactically correct for
    // parsers that only need the field count).
    let _ = writeln!(s, "cpu  0 0 0 0 0 0 0 0 0 0");
    for i in 0..ncpus {
        let _ = writeln!(s, "cpu{} 0 0 0 0 0 0 0 0 0 0", i);
    }

    // intr — total plus per-vector counts for every armed vector.
    let snaps = snapshot_counters();
    let total_intr: u64 = snaps.iter().map(|s| s.total).sum();
    let _ = write!(s, "intr {}", total_intr);
    // Emit per-vector counts for vectors 0..=255 with sparse gaps as 0.
    {
        let mut per_vec = [0u64; 256];
        for snap in &snaps {
            per_vec[snap.vector as usize] = snap.total;
        }
        for v in 0usize..256 {
            let _ = write!(s, " {}", per_vec[v]);
        }
    }
    let _ = writeln!(s);

    // ctxt: total context switches — scheduler doesn't track this yet.
    // Deferred: add a context_switch_counter atomic to narf-scheduler.
    let _ = writeln!(s, "ctxt 0");

    // btime: Unix timestamp of boot. Use wall-clock minus uptime.
    // If the wall clock hasn't been set (offset == 0) we report 0,
    // which is how a newly-booted Linux system looks before NTP sync.
    let uptime_ns = narf_time::monotonic_ns();
    let wall = narf_time::now_wall();
    let boot_secs = if wall.secs > 0 {
        let uptime_secs = (uptime_ns / 1_000_000_000) as i64;
        (wall.secs - uptime_secs).max(0)
    } else {
        0i64
    };
    let _ = writeln!(s, "btime {}", boot_secs);

    // processes: total forks since boot (scheduler doesn't expose
    // this counter today — deferred).
    let _ = writeln!(s, "processes 0");

    // procs_running / procs_blocked: live running/blocked task counts.
    // Use all_task_ids().len() as a conservative estimate for running.
    let nr_tasks = narf_scheduler::all_task_ids().len();
    let _ = writeln!(s, "procs_running {}", nr_tasks);
    let _ = writeln!(s, "procs_blocked 0");

    // softirq: total + per-type (all zeroed — deferred).
    // HI TIMER NET_TX NET_RX BLOCK IRQ_POLL TASKLET SCHED HRTIMER RCU
    let _ = writeln!(s, "softirq 0 0 0 0 0 0 0 0 0 0 0");

    s.into_bytes()
}

// ── /proc/diskstats ──────────────────────────────────────────────────
//
// Linux: block/genhd.c diskstats_show
// Format (Linux kernel 4.18+ with 18 fields):
//   major minor name reads_completed reads_merged sectors_read_ms
//   read_ms writes_completed writes_merged sectors_written write_ms
//   ios_in_progress total_io_ms weighted_io_ms
//   [discards_completed discards_merged sectors_discarded discard_ms]
//
// NARF block layer tracks no I/O counters today. All counters are zero.
// DEFERRED: wire per-device counters in narf-block registry.

fn gen_diskstats() -> Vec<u8> {
    let mut s = String::new();
    for (i, dev) in narf_block::block_devices().iter().enumerate() {
        let major = 8u32; // sda-style SCSI/NVMe placeholder major
        let minor = (i * 16) as u32;
        let _ = writeln!(
            s,
            "{:4} {:7} {:<20} 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0",
            major, minor, dev.name,
        );
    }
    s.into_bytes()
}

// ── /proc/interrupts ────────────────────────────────────────────────
//
// Linux: fs/proc/interrupts.c show_interrupts
// Header:       "           CPU0       CPU1\n"
// Body lines:   "   0:        123          0   IO-APIC   2-edge   timer\n"

fn gen_interrupts() -> Vec<u8> {
    let mut s = String::new();
    let ncpus = cpu_count().max(1) as usize;
    let per_cpu = ncpus.min(PERCPU_FIRES_MAX);

    // Header
    let _ = write!(s, "      ");
    for cpu in 0..per_cpu {
        let _ = write!(s, "      CPU{:<3}", cpu);
    }
    let _ = writeln!(s);

    // One line per non-empty vector
    let snaps = snapshot_counters();
    for snap in &snaps {
        let _ = write!(s, "{:>3}:", snap.vector);
        for cpu in 0..per_cpu {
            let _ = write!(s, " {:>10}", snap.per_cpu[cpu]);
        }
        // type + chip + action (simplified: "NARF" for chip)
        let action = if snap.handler_names.is_empty() {
            "(none)"
        } else {
            snap.handler_names[0]
        };
        let _ = writeln!(s, "   NARF   {}  {}", snap.vector, action);
    }

    // NMI / LOC / SPU synthetic lines (Linux always emits them)
    let _ = write!(s, "NMI:");
    for _ in 0..per_cpu {
        let _ = write!(s, " {:>10}", narf_interrupts::nmi_fire_count());
    }
    let _ = writeln!(s, "   Non-maskable interrupts");

    let _ = write!(s, "LOC:");
    for _ in 0..per_cpu {
        let _ = write!(s, " {:>10}", 0);
    }
    let _ = writeln!(s, "   Local timer interrupts");

    let _ = write!(s, "SPU:");
    for _ in 0..per_cpu {
        let _ = write!(s, " {:>10}", narf_interrupts::spurious_count(0xFF));
    }
    let _ = writeln!(s, "   Spurious interrupts");

    s.into_bytes()
}

// ── /proc/softirqs ──────────────────────────────────────────────────
//
// Linux: fs/proc/softirqs.c show_softirqs
// 10 standard types: HI TIMER NET_TX NET_RX BLOCK IRQ_POLL TASKLET
//                    SCHED HRTIMER RCU
// DEFERRED: wire real per-CPU softirq counters when the softirq
//           subsystem is implemented. All zero for now.

const SOFTIRQ_NAMES: [&str; 10] = [
    "HI", "TIMER", "NET_TX", "NET_RX", "BLOCK", "IRQ_POLL", "TASKLET", "SCHED", "HRTIMER", "RCU",
];

fn gen_softirqs() -> Vec<u8> {
    let mut s = String::new();
    let ncpus = cpu_count().max(1) as usize;
    let per_cpu = ncpus.min(PERCPU_FIRES_MAX);

    // Header
    let _ = write!(s, "                    ");
    for cpu in 0..per_cpu {
        let _ = write!(s, "      CPU{:<3}", cpu);
    }
    let _ = writeln!(s);

    // Body: all zeroes
    for name in SOFTIRQ_NAMES {
        let _ = write!(s, "{:>16}:", name);
        for _ in 0..per_cpu {
            let _ = write!(s, " {:>10}", 0u64);
        }
        let _ = writeln!(s);
    }
    s.into_bytes()
}

// ── /proc/swaps ──────────────────────────────────────────────────────
//
// Linux: mm/swapfile.c swap_show
// NARF has no swap space.

fn gen_swaps() -> Vec<u8> {
    "Filename\t\t\t\tType\t\tSize\t\tUsed\t\tPriority\n"
        .as_bytes()
        .to_vec()
}

// ── /proc/modules ────────────────────────────────────────────────────
//
// Linux: kernel/module/main.c m_show
// Format: "<name> <size> <refcnt> <holders> <state> 0x<addr>\n"
//
// DEFERRED: the Wave-21 LKM agent is expected to register its module
// list through `register_modules_snapshot_hook`. Until that hook exists
// we return an empty body so parsers don't fail on ENOENT.
//
// Wire-up note: when LKM lands, call:
//   aggregate::register_modules_snapshot_hook(fn() -> Vec<ModuleInfo>)
// and replace the stub body in gen_modules with the hook call.

fn gen_modules() -> Vec<u8> {
    // Empty body — no loadable modules yet.
    // See deferred note in module header.
    Vec::new()
}

// ── /proc/iomem ──────────────────────────────────────────────────────
//
// Linux: kernel/resource.c iomem_init_list / proc_iomem_show
// Format: "start-end : Region name\n" (hex, no 0x prefix)
//
// DEFERRED: narf-memory's E820 / ACPI memmap export and the PCIe BAR
// layout haven't been plumbed into a snapshot API yet.
// Placeholder matches the Linux minimal-boot look (single System RAM
// region). Real wiring will land when MM region snapshot is available.

fn gen_iomem() -> Vec<u8> {
    let mut s = String::new();
    let fs = narf_memory::frame_stats();
    // Approximate: total frames * 4 KiB starting at physical 0.
    let end = (fs.total as u64) * 4096;
    if end > 0 {
        let _ = writeln!(s, "00000000-{:08x} : System RAM", end.saturating_sub(1));
    } else {
        let _ = writeln!(s, "00000000-00000000 : System RAM");
    }
    s.into_bytes()
}

// ── /proc/ioports ────────────────────────────────────────────────────
//
// Linux: arch/x86/kernel/ioport.c / kernel/resource.c
// Format: "start-end : Region name\n" (4-digit hex ports)
//
// DEFERRED: x86 I/O port allocations aren't tracked yet.

fn gen_ioports() -> Vec<u8> {
    let mut s = String::new();
    let _ = writeln!(s, "0000-ffff : PCI Bus 0000:00");
    let _ = writeln!(s, "  0000-001f : dma1");
    let _ = writeln!(s, "  0020-0021 : pic1");
    let _ = writeln!(s, "  0040-0043 : timer0");
    let _ = writeln!(s, "  0060-0060 : keyboard");
    let _ = writeln!(s, "  0070-0077 : rtc0");
    let _ = writeln!(s, "  0080-008f : dma page reg");
    let _ = writeln!(s, "  00a0-00a1 : pic2");
    let _ = writeln!(s, "  00c0-00df : dma2");
    let _ = writeln!(s, "  00f0-00ff : fpu");
    s.into_bytes()
}

// ── /proc/slabinfo ───────────────────────────────────────────────────
//
// Linux: mm/slab.c slab_proc_show (slabinfo version 2.1)
// Format:
//   slabinfo - version: 2.1
//   # name <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab>
//   #     : tunables <limit> <batchcount> <sharedfactor>
//   #     : slabdata <active_slabs> <num_slabs> <sharedavail>
//   <name> <active> <total> <objsize> <objperslab> <pagesperslab>
//          : tunables 0 0 0 : slabdata <active_slabs> <total_slabs> 0

fn gen_slabinfo() -> Vec<u8> {
    let mut s = String::new();
    let _ = writeln!(s, "slabinfo - version: 2.1");
    let _ = writeln!(
        s,
        "# name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab> \
         : tunables <limit> <batchcount> <sharedfactor> \
         : slabdata <active_slabs> <num_slabs> <sharedavail>"
    );

    let stats = narf_memory::slab::stats();
    for cls in stats.classes.iter() {
        if cls.block_size == 0 {
            continue;
        }
        let objs_per_slab = if cls.block_size > 0 {
            (narf_memory::PAGE_SIZE as usize) / cls.block_size
        } else {
            1
        };
        let objs_per_slab = objs_per_slab.max(1);
        // active_slabs ≈ ceil(in_use / objs_per_slab).
        let active_slabs = cls.in_use.div_ceil(objs_per_slab);
        let total_slabs = cls.grown.div_ceil(objs_per_slab);
        let _ = writeln!(
            s,
            "kmalloc-{:<6} {:>8} {:>8} {:>8} {:>8} {:>12} \
             : tunables 0 0 0 \
             : slabdata {:>8} {:>8} 0",
            cls.block_size,
            cls.in_use,
            cls.grown,
            cls.block_size,
            objs_per_slab,
            1, // pages per slab — 1 for small classes
            active_slabs,
            total_slabs,
        );
    }
    s.into_bytes()
}

// ── /proc/vmstat ─────────────────────────────────────────────────────
//
// Linux: mm/vmstat.c vmstat_show
// ~80 counters. NARF tracks only a handful today.
// DEFERRED: add tracking atomics in narf-memory for each counter.

fn gen_vmstat() -> Vec<u8> {
    let mut s = String::new();
    let fs = narf_memory::frame_stats();

    // The counts we CAN populate from existing APIs.
    let _ = writeln!(s, "nr_free_pages {}", fs.free);
    let _ = writeln!(s, "nr_zone_active_anon 0");
    let _ = writeln!(s, "nr_zone_inactive_anon 0");
    let _ = writeln!(s, "nr_zone_active_file 0");
    let _ = writeln!(s, "nr_zone_inactive_file 0");
    let _ = writeln!(s, "nr_zone_unevictable 0");
    let _ = writeln!(s, "nr_zone_write_pending 0");
    let _ = writeln!(s, "nr_mlock 0");
    let _ = writeln!(s, "nr_bounce 0");
    let _ = writeln!(s, "nr_slab_reclaimable 0");
    let _ = writeln!(
        s,
        "nr_slab_unreclaimable {}",
        narf_memory::slab::stats().large_in_use
    );
    let _ = writeln!(s, "nr_page_table_pages 0");
    let _ = writeln!(s, "nr_kernel_stack 0");
    let _ = writeln!(s, "nr_anon_pages 0");
    let _ = writeln!(s, "nr_mapped 0");
    let _ = writeln!(s, "nr_file_pages 0");
    let _ = writeln!(s, "nr_dirty 0");
    let _ = writeln!(s, "nr_writeback 0");
    let _ = writeln!(s, "nr_writeback_temp 0");
    let _ = writeln!(s, "nr_shmem 0");
    let _ = writeln!(s, "nr_shmem_hugepages 0");
    let _ = writeln!(s, "nr_shmem_pmdmapped 0");
    let _ = writeln!(s, "nr_file_hugepages 0");
    let _ = writeln!(s, "nr_file_pmdmapped 0");
    let _ = writeln!(s, "nr_anon_transparent_hugepages 0");
    let _ = writeln!(s, "nr_vmscan_write 0");
    let _ = writeln!(s, "nr_vmscan_immediate_reclaim 0");
    let _ = writeln!(s, "nr_dirtied 0");
    let _ = writeln!(s, "nr_written 0");
    let _ = writeln!(s, "nr_kernel_misc_reclaimable 0");
    let _ = writeln!(s, "nr_foll_pin_acquired 0");
    let _ = writeln!(s, "nr_foll_pin_released 0");
    let _ = writeln!(s, "numa_hit 0");
    let _ = writeln!(s, "numa_miss 0");
    let _ = writeln!(s, "numa_foreign 0");
    let _ = writeln!(s, "numa_interleave 0");
    let _ = writeln!(s, "numa_local 0");
    let _ = writeln!(s, "numa_other 0");
    let _ = writeln!(s, "pgpgin 0");
    let _ = writeln!(s, "pgpgout 0");
    let _ = writeln!(s, "pswpin 0");
    let _ = writeln!(s, "pswpout 0");
    let _ = writeln!(s, "pgalloc_dma 0");
    let _ = writeln!(s, "pgalloc_dma32 0");
    let _ = writeln!(s, "pgalloc_normal {}", fs.total.saturating_sub(fs.free));
    let _ = writeln!(s, "pgalloc_movable 0");
    let _ = writeln!(s, "pgalloc_device 0");
    let _ = writeln!(s, "allocstall_dma 0");
    let _ = writeln!(s, "allocstall_dma32 0");
    let _ = writeln!(s, "allocstall_normal 0");
    let _ = writeln!(s, "allocstall_movable 0");
    let _ = writeln!(s, "allocstall_device 0");
    let _ = writeln!(s, "pgskip_dma 0");
    let _ = writeln!(s, "pgskip_dma32 0");
    let _ = writeln!(s, "pgskip_normal 0");
    let _ = writeln!(s, "pgskip_movable 0");
    let _ = writeln!(s, "pgskip_device 0");
    let _ = writeln!(s, "pgfree {}", fs.free);
    let _ = writeln!(s, "pgactivate 0");
    let _ = writeln!(s, "pgdeactivate 0");
    let _ = writeln!(s, "pglazyfree 0");
    let _ = writeln!(s, "pglazyfreed 0");
    let _ = writeln!(s, "pgfault 0");
    let _ = writeln!(s, "pgmajfault 0");
    let _ = writeln!(s, "pgrefill 0");
    let _ = writeln!(s, "pgreuse 0");
    let _ = writeln!(s, "pgsteal_kswapd 0");
    let _ = writeln!(s, "pgsteal_direct 0");
    let _ = writeln!(s, "pgdemote_kswapd 0");
    let _ = writeln!(s, "pgdemote_direct 0");
    let _ = writeln!(s, "pgscan_kswapd 0");
    let _ = writeln!(s, "pgscan_direct 0");
    let _ = writeln!(s, "pgscan_direct_throttle 0");
    let _ = writeln!(s, "pgscan_anon 0");
    let _ = writeln!(s, "pgscan_file 0");
    let _ = writeln!(s, "pgsteal_anon 0");
    let _ = writeln!(s, "pgsteal_file 0");
    let _ = writeln!(s, "zone_reclaim_failed 0");
    let _ = writeln!(s, "pginodesteal 0");
    let _ = writeln!(s, "slabs_scanned 0");
    let _ = writeln!(s, "kswapd_inodesteal 0");
    let _ = writeln!(s, "kswapd_low_wmark_hit_quickly 0");
    let _ = writeln!(s, "kswapd_high_wmark_hit_quickly 0");
    let _ = writeln!(s, "pageoutrun 0");
    let _ = writeln!(s, "pgrotated 0");
    let _ = writeln!(s, "drop_pagecache 0");
    let _ = writeln!(s, "drop_slab 0");
    let _ = writeln!(s, "oom_kill 0");
    let _ = writeln!(s, "thp_fault_alloc 0");
    let _ = writeln!(s, "thp_fault_fallback 0");
    let _ = writeln!(s, "thp_collapse_alloc 0");
    let _ = writeln!(s, "thp_collapse_alloc_failed 0");

    s.into_bytes()
}

// ── /proc/zoneinfo ───────────────────────────────────────────────────
//
// Linux: mm/vmstat.c zoneinfo_show
// NARF uses SRAT-derived NUMA topology.

fn gen_zoneinfo() -> Vec<u8> {
    let mut s = String::new();
    let fs = narf_memory::frame_stats();
    let numa_aware = narf_memory::is_numa_aware();
    let max_nodes = if numa_aware {
        narf_memory::FRAME_MAX_NUMA_NODES
    } else {
        1
    };

    for node in 0..max_nodes {
        let node_free = narf_memory::node_free(node);
        if node_free == 0 && node > 0 {
            // Skip empty NUMA nodes (not yet online).
            continue;
        }
        let _ = writeln!(s, "Node {}, zone   Normal", node);
        let _ = writeln!(s, "  per-node stats");
        let _ = writeln!(s, "      nr_inactive_anon 0");
        let _ = writeln!(s, "      nr_active_anon 0");
        let _ = writeln!(s, "      nr_inactive_file 0");
        let _ = writeln!(s, "      nr_active_file 0");
        let _ = writeln!(s, "      nr_unevictable 0");
        let _ = writeln!(s, "      nr_slab_reclaimable 0");
        let _ = writeln!(s, "      nr_slab_unreclaimable 0");
        let _ = writeln!(s, "      nr_isolated_anon 0");
        let _ = writeln!(s, "      nr_isolated_file 0");
        let _ = writeln!(s, "      workingset_nodes 0");
        let _ = writeln!(s, "      nr_anon_pages 0");
        let _ = writeln!(s, "      nr_mapped 0");
        let _ = writeln!(s, "      nr_file_pages 0");
        let _ = writeln!(s, "      nr_dirty 0");
        let _ = writeln!(s, "      nr_writeback 0");
        let _ = writeln!(s, "      nr_writeback_temp 0");
        let _ = writeln!(s, "      nr_shmem 0");
        let _ = writeln!(s, "      nr_shmem_hugepages 0");
        let _ = writeln!(s, "      nr_shmem_pmdmapped 0");
        let _ = writeln!(s, "      nr_file_hugepages 0");
        let _ = writeln!(s, "      nr_file_pmdmapped 0");
        let _ = writeln!(s, "      nr_anon_transparent_hugepages 0");
        let _ = writeln!(s, "      nr_vmscan_write 0");
        let _ = writeln!(s, "      nr_vmscan_immediate_reclaim 0");
        let _ = writeln!(s, "      nr_dirtied 0");
        let _ = writeln!(s, "      nr_written 0");
        // Per-zone fields
        let total = if node == 0 { fs.total } else { node_free };
        let _ = writeln!(s, "  pages free     {}", node_free);
        let _ = writeln!(s, "        min      0");
        let _ = writeln!(s, "        low      0");
        let _ = writeln!(s, "        high     0");
        let _ = writeln!(s, "        spanned  {}", total);
        let _ = writeln!(s, "        present  {}", total);
        let _ = writeln!(s, "        managed  {}", total);
        let _ = writeln!(s, "  pagesets");
        let ncpus = cpu_count().max(1) as usize;
        for cpu in 0..ncpus {
            let _ = writeln!(s, "    cpu: {}", cpu);
            let _ = writeln!(s, "              count: 0");
            let _ = writeln!(s, "              high:  0");
            let _ = writeln!(s, "              batch: 1");
            let _ = writeln!(s, "  vm stats threshold: 0");
        }
        let _ = writeln!(s, "  all_unreclaimable: 0");
        let _ = writeln!(s, "  start_pfn:         0");
        let _ = writeln!(s, "  inactive_ratio:    1");
    }
    s.into_bytes()
}

// ── /proc/buddyinfo ──────────────────────────────────────────────────
//
// Linux: mm/vmstat.c buddyinfo_show
// Format: "Node <n>, zone <name> <order-0> <order-1> ... <order-10>\n"
// NARF buddy has max-order 10 (MAX_ORDER from memory crate).

fn gen_buddyinfo() -> Vec<u8> {
    let mut s = String::new();
    let max_nodes = if narf_memory::is_numa_aware() {
        narf_memory::FRAME_MAX_NUMA_NODES
    } else {
        1
    };

    for node in 0..max_nodes {
        let node_free = narf_memory::node_free(node);
        if node_free == 0 && node > 0 {
            continue;
        }
        let _ = write!(s, "Node {}, zone   Normal", node);
        // We don't have per-order counters exposed; emit zeroes.
        // DEFERRED: expose BuddyZone::free_at_order(order) snapshot.
        for _order in 0..11 {
            let _ = write!(s, "  0");
        }
        let _ = writeln!(s);
    }
    s.into_bytes()
}

// ── /proc/pagetypeinfo ───────────────────────────────────────────────
//
// Linux: mm/vmstat.c pagetypeinfo_show
// DEFERRED: migration-type (Unmovable/Movable/Reclaimable/etc.) counters
// not tracked yet.

fn gen_pagetypeinfo() -> Vec<u8> {
    let mut s = String::new();
    let _ = writeln!(s, "Page block order: 9");
    let _ = writeln!(s, "Pages per block:  512");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "Free pages count per migrate type at order       \
         0  1  2  3  4  5  6  7  8  9 10"
    );
    for node in 0..1usize {
        for (zone, zone_name) in [("Normal", "Normal"), ("DMA32", "DMA32")].iter() {
            let _ = writeln!(
                s,
                "Node {:4}, zone {:8}, type    Unmovable   0  0  0  0  0  0  0  0  0  0  0",
                node, zone_name
            );
            let _ = writeln!(
                s,
                "Node {:4}, zone {:8}, type      Movable   0  0  0  0  0  0  0  0  0  0  0",
                node, zone_name
            );
            let _ = writeln!(
                s,
                "Node {:4}, zone {:8}, type  Reclaimable   0  0  0  0  0  0  0  0  0  0  0",
                node, zone_name
            );
            let _ = writeln!(
                s,
                "Node {:4}, zone {:8}, type   HighAtomic   0  0  0  0  0  0  0  0  0  0  0",
                node, zone_name
            );
            let _ = writeln!(
                s,
                "Node {:4}, zone {:8}, type      Isolate   0  0  0  0  0  0  0  0  0  0  0",
                node, zone_name
            );
            let _ = zone; // suppress dead-code warning on the tuple element
        }
    }
    s.into_bytes()
}

// ── /proc/timer_list ─────────────────────────────────────────────────
//
// Linux: kernel/time/timer_list.c show_timer_list
// NARF uses a timer-wheel in narf-time::timer_wheel.

fn gen_timer_list() -> Vec<u8> {
    let mut s = String::new();
    let _ = writeln!(s, "Timer List Version: v0.9");
    let _ = writeln!(s, "HRTIMER_MAX_CLOCK_BASES: 4");
    let _ = writeln!(s, "now at {} nsecs", narf_time::monotonic_ns());
    let _ = writeln!(s);
    let _ = writeln!(s, "cpu: 0");
    let occupied = narf_time::timer_wheel::occupied();
    if occupied == 0 {
        let _ = writeln!(s, " no timers pending");
    } else {
        let _ = writeln!(s, " pending timers: {}", occupied);
        if let Some(next) = narf_time::timer_wheel::next_deadline_cycles() {
            let cpns = narf_time::cycles_per_ns() as u64;
            let next_ns = if cpns > 0 { next / cpns } else { next };
            let _ = writeln!(s, " next deadline: {} nsecs", next_ns);
        }
    }
    s.into_bytes()
}

// ── /proc/locks ──────────────────────────────────────────────────────
//
// Linux: fs/locks.c locks_seq_show
// NARF has minimal lock support (no POSIX file-lock tracking yet).

fn gen_locks() -> Vec<u8> {
    // Linux returns an empty body when no locks are held.
    // NARF has no POSIX file-lock tracking yet — return empty.
    // DEFERRED: wire to a lock-registry snapshot when POSIX locks land.
    Vec::new()
}

// ── /proc/devices ────────────────────────────────────────────────────
//
// Linux: fs/proc/devices.c devinfo_show
// Static allocation table — matches Wave-19 bridge decisions.

fn gen_devices() -> Vec<u8> {
    let mut s = String::new();
    let _ = writeln!(s, "Character devices:");
    let _ = writeln!(s, "  1 mem");
    let _ = writeln!(s, "  4 /dev/vc/0");
    let _ = writeln!(s, "  5 /dev/tty");
    let _ = writeln!(s, "  5 /dev/console");
    let _ = writeln!(s, "  5 /dev/ptmx");
    let _ = writeln!(s, "  7 vcs");
    let _ = writeln!(s, " 10 misc");
    let _ = writeln!(s, " 13 input");
    let _ = writeln!(s, " 29 fb");
    let _ = writeln!(s, " 89 i2c");
    let _ = writeln!(s, " 90 mtd");
    let _ = writeln!(s, "116 alsa");
    let _ = writeln!(s, "128 ptm");
    let _ = writeln!(s, "136 pts");
    let _ = writeln!(s, "180 usb");
    let _ = writeln!(s, "189 usb_device");
    let _ = writeln!(s, "202 cpu/msr");
    let _ = writeln!(s, "203 cpu/cpuid");
    let _ = writeln!(s, "226 drm");
    let _ = writeln!(s, "234 nvme");
    let _ = writeln!(s, "235 ttyUSB");
    let _ = writeln!(s);
    let _ = writeln!(s, "Block devices:");
    let _ = writeln!(s, "  1 ramdisk");
    let _ = writeln!(s, "  7 loop");
    let _ = writeln!(s, "  8 sd");
    let _ = writeln!(s, " 11 sr");
    let _ = writeln!(s, " 65 sd");
    let _ = writeln!(s, "252 virtblk");
    let _ = writeln!(s, "253 device-mapper");
    let _ = writeln!(s, "259 blkext");
    s.into_bytes()
}

// ── /proc/filesystems (annotated) ───────────────────────────────────
//
// Linux: fs/filesystems.c filesystems_proc_show
// Extends the basic version in mod.rs by adding the "nodev" annotation
// that procps-ng, mount(8), and findmnt(8) rely on.

fn gen_filesystems_annotated() -> Vec<u8> {
    use alloc::collections::BTreeSet;

    let names: BTreeSet<String> = crate::registry()
        .list_with_names()
        .into_iter()
        .map(|(_p, n)| n)
        .collect();

    let mut s = String::new();
    // Always include the standard NARF FS types as nodev.
    let nodev_always = &["sysfs", "proc", "devtmpfs", "devpts", "tmpfs", "9p"];
    for n in nodev_always {
        let _ = writeln!(s, "nodev\t{}", n);
    }
    // Mounted instances.
    for n in &names {
        if nodev_always.contains(&n.as_str()) {
            continue;
        }
        // Block-backed FS types get no "nodev" prefix.
        if n == "ext2" || n == "ext4" || n == "fat" || n == "vfat" || n == "minix" {
            let _ = writeln!(s, "\t{}", n);
        } else {
            let _ = writeln!(s, "nodev\t{}", n);
        }
    }
    s.into_bytes()
}

// ── /proc/consoles ───────────────────────────────────────────────────
//
// Linux: kernel/printk/printk.c console_show
// Format: "<name> <flags> <major>:<minor>"
// Flags (subset): E=enabled, C=CON_CONSDEV, p=printk, b=bind, a=anmatch.

fn gen_consoles() -> Vec<u8> {
    let mut s = String::new();
    // NARF has a UART console and an FB console.
    // Major 4 = ttyS, minor 64 = ttyS0.
    // Major 5 = tty console, minor 1 = /dev/console.
    let _ = writeln!(s, "tty0                 -WU (EC p  ) 4:0");
    let _ = writeln!(s, "ttyS0                -W- (E  p  ) 4:64");
    s.into_bytes()
}

// ── /proc/misc ───────────────────────────────────────────────────────
//
// Linux: drivers/char/misc.c misc_seq_show
// Format: "<minor> <name>\n"
// Major 10 is misc.

fn gen_misc() -> Vec<u8> {
    let mut s = String::new();
    // Standard misc devices.
    let _ = writeln!(s, "229 fuse");
    let _ = writeln!(s, "200 tun");
    let _ = writeln!(s, "183 hw_random");
    let _ = writeln!(s, "135 watchdog");
    let _ = writeln!(s, "  1 psaux");
    s.into_bytes()
}

// ── /proc/tty/drivers ────────────────────────────────────────────────
//
// Linux: drivers/tty/tty_io.c proc_tty_init + proc_tty_show
// Format: "<name> <major> <minor-start> <minor-end> <type>\n"

fn gen_tty_drivers() -> Vec<u8> {
    let mut s = String::new();
    let _ = writeln!(s, "/dev/tty             5   0   0 system:/dev/tty");
    let _ = writeln!(s, "/dev/console         5   1   1 system:console");
    let _ = writeln!(s, "/dev/ptmx            5   2   2 system");
    let _ = writeln!(s, "/dev/vc/0            4   0   0 system:vtmaster");
    let _ = writeln!(s, "serial               4  64 111 serial");
    s.into_bytes()
}

// ── /proc/fb ─────────────────────────────────────────────────────────
//
// Linux: drivers/video/fbdev/core/fbsysfs.c / proc_fb_show
// Format: "<idx> <name>\n"

fn gen_fb() -> Vec<u8> {
    let mut s = String::new();
    // narf-fb is not a direct dependency of narf-filesystem to avoid the
    // dep chain narf-filesystem → narf-fb → narf-graphics-driver → …
    // The framebuffer procfs file is populated with a static placeholder.
    // DEFERRED: register a `FbInfoHook` fn-pointer (like the scheduler
    // task-info hook) so narf-fb can push its scanout name at boot.
    let _ = writeln!(s, "0 NARF generic framebuffer");
    s.into_bytes()
}

// ── /proc/crypto ─────────────────────────────────────────────────────
//
// Linux: crypto/proc.c crypto_info_show
// Format: multi-line blocks per algorithm:
//   name     : sha256
//   driver   : sha256-generic
//   module   : kernel
//   priority : 100
//   refcnt   : 1
//   selftest : passed
//   internal : no
//   type     : shash
//   blocksize: 64
//   digestsize: 32

fn gen_crypto() -> Vec<u8> {
    let mut s = String::new();

    // Known NARF crypto algorithms from narf-crypto.
    // These match the implementations in crypto/src/*.rs.
    let algorithms: &[(&str, &str, u32, &str, &str)] = &[
        // (name, type, priority, blocksize, extra)
        ("sha256", "shash", 100, "64", "digestsize: 32"),
        ("sha512", "shash", 100, "128", "digestsize: 64"),
        ("sha1", "shash", 100, "64", "digestsize: 20"),
        (
            "chacha20-poly1305",
            "aead",
            100,
            "64",
            "ivsize: 12\nauthsize: 16\nmaxauthsize: 16",
        ),
        (
            "aes-xts",
            "skcipher",
            100,
            "16",
            "min keysize: 64\nmax keysize: 64\nivsize: 16\nchunksize: 16\nwalksize: 16",
        ),
        ("ed25519", "akcipher", 100, "0", ""),
        ("curve25519", "kpp", 100, "0", ""),
        ("hmac-sha1", "shash", 100, "64", "digestsize: 20"),
        ("cmac-aes128", "shash", 100, "16", "digestsize: 16"),
        (
            "aes-gcm",
            "aead",
            100,
            "16",
            "ivsize: 12\nauthsize: 16\nmaxauthsize: 16",
        ),
    ];

    for (name, alg_type, prio, blocksize, extra) in algorithms {
        let _ = writeln!(s, "name         : {}", name);
        let _ = writeln!(s, "driver       : {}-narf", name);
        let _ = writeln!(s, "module       : kernel");
        let _ = writeln!(s, "priority     : {}", prio);
        let _ = writeln!(s, "refcnt       : 1");
        let _ = writeln!(s, "selftest     : passed");
        let _ = writeln!(s, "internal     : no");
        let _ = writeln!(s, "type         : {}", alg_type);
        let _ = writeln!(s, "blocksize    : {}", blocksize);
        if !extra.is_empty() {
            for line in extra.lines() {
                let _ = writeln!(s, "{}", line);
            }
        }
        let _ = writeln!(s);
    }
    s.into_bytes()
}

// ── Tests (≥12 smokes) ───────────────────────────────────────────────

use narf_kernel_test::{kernel_test_in, TestResult};

fn read_registered(path: &[&str]) -> Option<Vec<u8>> {
    use super::{lookup_registry, ProcNodeSnapshot};
    match lookup_registry(path) {
        Some(ProcNodeSnapshot::File(f)) => Some(f.read()),
        _ => None,
    }
}

/// /proc/diskstats: one line per registered block device.
fn smoke_diskstats_one_line_per_device() -> TestResult {
    use narf_block::registry::{__reset_for_test, __restore_for_test, __snapshot_for_test};
    let saved = __snapshot_for_test();
    __reset_for_test();
    // Register two synthetic devices.
    use alloc::sync::Arc;
    use narf_block::registry::{register_block_device, BlockDeviceSync, BlockIoError};
    struct NullDev;
    impl BlockDeviceSync for NullDev {
        fn lba_size(&self) -> u32 {
            512
        }
        fn capacity(&self) -> u64 {
            2048
        }
        fn read(&self, _: u64, _: u16, _: &mut [u8]) -> Result<(), BlockIoError> {
            Ok(())
        }
        fn write(&self, _: u64, _: u16, _: &[u8]) -> Result<(), BlockIoError> {
            Ok(())
        }
    }
    register_block_device("smoke0", Arc::new(NullDev));
    register_block_device("smoke1", Arc::new(NullDev));
    register_all();
    let body = match read_registered(&["diskstats"]) {
        Some(b) => b,
        None => {
            __restore_for_test(saved);
            return TestResult::Fail("diskstats not registered");
        }
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => {
            __restore_for_test(saved);
            return TestResult::Fail("diskstats not utf-8");
        }
    };
    let line_count = text.lines().count();
    __restore_for_test(saved);
    if line_count >= 2 {
        TestResult::Pass
    } else {
        TestResult::Fail("diskstats: expected ≥2 lines for 2 devices")
    }
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_diskstats_one_line_per_device
);

/// /proc/interrupts: header columns match CPU count.
fn smoke_interrupts_header_matches_cpu_count() -> TestResult {
    register_all();
    let body = match read_registered(&["interrupts"]) {
        Some(b) => b,
        None => return TestResult::Fail("interrupts not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("interrupts not utf-8"),
    };
    // First line is header — check it contains at least one "CPU" token.
    let header = text.lines().next().unwrap_or("");
    if header.contains("CPU0") {
        TestResult::Pass
    } else {
        TestResult::Fail("interrupts: header missing CPU0 column")
    }
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_interrupts_header_matches_cpu_count
);

/// /proc/softirqs: all 10 standard type names are present.
fn smoke_softirqs_has_all_ten_types() -> TestResult {
    register_all();
    let body = match read_registered(&["softirqs"]) {
        Some(b) => b,
        None => return TestResult::Fail("softirqs not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("softirqs not utf-8"),
    };
    for name in SOFTIRQ_NAMES {
        if !text.contains(name) {
            return TestResult::Fail("softirqs: missing expected type");
        }
    }
    TestResult::Pass
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_softirqs_has_all_ten_types
);

/// /proc/stat: has cpu aggregate line + per-cpu line + ctxt + btime.
fn smoke_stat_has_cpu_and_ctxt_btime() -> TestResult {
    register_all();
    let body = match read_registered(&["stat"]) {
        Some(b) => b,
        None => return TestResult::Fail("stat not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("stat not utf-8"),
    };
    let has_cpu = text.lines().any(|l| l.starts_with("cpu "));
    let has_cpu0 = text.lines().any(|l| l.starts_with("cpu0 "));
    let has_ctxt = text.lines().any(|l| l.starts_with("ctxt "));
    let has_btime = text.lines().any(|l| l.starts_with("btime "));
    if has_cpu && has_cpu0 && has_ctxt && has_btime {
        TestResult::Pass
    } else {
        TestResult::Fail("stat: missing required fields")
    }
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_stat_has_cpu_and_ctxt_btime
);

/// /proc/swaps: header line only.
fn smoke_swaps_header_only() -> TestResult {
    register_all();
    let body = match read_registered(&["swaps"]) {
        Some(b) => b,
        None => return TestResult::Fail("swaps not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("swaps not utf-8"),
    };
    if text.contains("Filename") {
        TestResult::Pass
    } else {
        TestResult::Fail("swaps: header line missing")
    }
}
kernel_test_in!("filesystem/procfs/aggregate", smoke_swaps_header_only);

/// /proc/slabinfo: version 2.1 header.
fn smoke_slabinfo_version_header() -> TestResult {
    register_all();
    let body = match read_registered(&["slabinfo"]) {
        Some(b) => b,
        None => return TestResult::Fail("slabinfo not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("slabinfo not utf-8"),
    };
    if text.starts_with("slabinfo - version: 2.1") {
        TestResult::Pass
    } else {
        TestResult::Fail("slabinfo: version 2.1 header missing")
    }
}
kernel_test_in!("filesystem/procfs/aggregate", smoke_slabinfo_version_header);

/// /proc/devices: contains both Character devices + Block devices sections.
fn smoke_devices_has_both_sections() -> TestResult {
    register_all();
    let body = match read_registered(&["devices"]) {
        Some(b) => b,
        None => return TestResult::Fail("devices not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("devices not utf-8"),
    };
    if text.contains("Character devices:") && text.contains("Block devices:") {
        TestResult::Pass
    } else {
        TestResult::Fail("devices: missing Character or Block section")
    }
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_devices_has_both_sections
);

/// /proc/filesystems (annotated): contains both "proc" and "sysfs".
fn smoke_filesystems_contains_proc_and_sysfs() -> TestResult {
    register_all();
    let body = match read_registered(&["filesystems"]) {
        Some(b) => b,
        None => return TestResult::Fail("filesystems not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("filesystems not utf-8"),
    };
    if text.contains("proc") && text.contains("sysfs") {
        TestResult::Pass
    } else {
        TestResult::Fail("filesystems: missing proc or sysfs")
    }
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_filesystems_contains_proc_and_sysfs
);

/// /proc/consoles: format has "tty" prefix and major:minor.
fn smoke_consoles_format() -> TestResult {
    register_all();
    let body = match read_registered(&["consoles"]) {
        Some(b) => b,
        None => return TestResult::Fail("consoles not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("consoles not utf-8"),
    };
    // Expect at least one line with a colon in the major:minor field.
    let has_colon = text
        .lines()
        .any(|l| l.contains(':') && (l.contains("tty") || l.contains("ttyS")));
    if has_colon {
        TestResult::Pass
    } else {
        TestResult::Fail("consoles: missing expected format")
    }
}
kernel_test_in!("filesystem/procfs/aggregate", smoke_consoles_format);

/// /proc/iomem: default placeholder line exists.
fn smoke_iomem_default_line() -> TestResult {
    register_all();
    let body = match read_registered(&["iomem"]) {
        Some(b) => b,
        None => return TestResult::Fail("iomem not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("iomem not utf-8"),
    };
    if text.contains("System RAM") {
        TestResult::Pass
    } else {
        TestResult::Fail("iomem: expected 'System RAM' placeholder")
    }
}
kernel_test_in!("filesystem/procfs/aggregate", smoke_iomem_default_line);

/// /proc/timer_list: header is present.
fn smoke_timer_list_header() -> TestResult {
    register_all();
    let body = match read_registered(&["timer_list"]) {
        Some(b) => b,
        None => return TestResult::Fail("timer_list not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("timer_list not utf-8"),
    };
    if text.contains("Timer List Version") {
        TestResult::Pass
    } else {
        TestResult::Fail("timer_list: header missing")
    }
}
kernel_test_in!("filesystem/procfs/aggregate", smoke_timer_list_header);

/// /proc/crypto: returns algorithm list with at least sha256.
fn smoke_crypto_returns_algorithms() -> TestResult {
    register_all();
    let body = match read_registered(&["crypto"]) {
        Some(b) => b,
        None => return TestResult::Fail("crypto not registered"),
    };
    let text = match String::from_utf8(body) {
        Ok(t) => t,
        Err(_) => return TestResult::Fail("crypto not utf-8"),
    };
    if text.contains("sha256") && text.contains("type") && text.contains("selftest") {
        TestResult::Pass
    } else {
        TestResult::Fail("crypto: expected sha256 algorithm entry")
    }
}
kernel_test_in!(
    "filesystem/procfs/aggregate",
    smoke_crypto_returns_algorithms
);
