[package]
name = "narf-tpm"
version = "0.1.0"
edition = "2021"

[dependencies]
narf-lib = { path = "../lib" }
narf-capabilities = { path = "../capabilities" }
narf-crypto = { path = "../crypto" }
async-trait = "0.1"
futures = { version = "0.3", default-features = false }
narf-kernel-test = { path = "../verification/kernel-test" }

[features]
kernel-test = []
