[package]
name         = "narf-input-driver"
description  = "Input drivers: i8042 PS/2 keyboard (x86_64) + future."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lib]
name = "narf_input_driver"
path = "src/lib.rs"

[dependencies]
narf-lib            = { path = "../../lib", version = "0.1.0" }
narf-input          = { path = "../../input", version = "0.1.0" }
narf-arch           = { path = "../../arch", version = "0.1.0" }
narf-time           = { path = "../../time", version = "0.1.0" }
narf-interrupts     = { path = "../../interrupts", version = "0.1.0" }
narf-acpi           = { path = "../../acpi", version = "0.1.0" }
narf-drivers        = { path = "../../drivers", version = "0.1.0" }
narf-init           = { path = "../../init", version = "0.1.0" }
narf-drivers-i2c    = { path = "../i2c", version = "0.1.0" }
narf-drivers-gpio   = { path = "../gpio", version = "0.1.0" }
narf-hid            = { path = "../../hid", version = "0.1.0" }
narf-scheduler      = { path = "../../scheduler", version = "0.1.0" }
narf-aml            = { path = "../../aml", version = "0.1.0" }
narf-fb             = { path = "../../fb", version = "0.1.0" }
narf-console        = { path = "../../console", version = "0.1.0" }
narf-drivers-virtio = { path = "../virtio", version = "0.1.0" }
narf-kernel-test    = { path = "../../verification/kernel-test", version = "0.1.0" }
async-trait         = "0.1"

[lints]
workspace = true
