// inotify smoke. Create an instance, add a watch (and confirm re-adding
// the same path returns the same wd while a different path gets a new
// one), then remove the watch and confirm a double-remove fails. Events
// are not generated by NARF's in-memory FSes yet, so this exercises the
// watch-descriptor bookkeeping. Success token "inotify-ok".
//
// Build: see REGEN_inotify_smoke.sh (musl-gcc, static-PIE).
#define _GNU_SOURCE
#include <unistd.h>
#include <string.h>
#include <sys/inotify.h>

static void w(const char *m) { write(1, m, strlen(m)); }

int main(void) {
    int fd = inotify_init1(IN_NONBLOCK);
    if (fd < 0) { w("inotify-fail: init\n"); return 1; }

    int wd = inotify_add_watch(fd, "/dev/shm", IN_CREATE | IN_DELETE);
    if (wd < 0) { w("inotify-fail: add\n"); return 1; }

    int wd2 = inotify_add_watch(fd, "/dev/shm", IN_CREATE);
    if (wd2 != wd) { w("inotify-fail: rewatch\n"); return 1; }

    int wd3 = inotify_add_watch(fd, "/", IN_CREATE);
    if (wd3 < 0 || wd3 == wd) { w("inotify-fail: add2\n"); return 1; }

    if (inotify_rm_watch(fd, wd) != 0) { w("inotify-fail: rm\n"); return 1; }
    if (inotify_rm_watch(fd, wd) == 0) { w("inotify-fail: rm-twice\n"); return 1; }

    close(fd);
    w("inotify-ok\n");
    return 0;
}
